version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: astrostats-bot:local
    env_file:
      - .env
    restart: unless-stopped
    # No inbound ports needed; the bot connects out to Discord
