# League related constants
LEAGUE_REGIONS = [
    "EUW1", "EUN1", "TR1", "RU", "NA1", "BR1", "LA1", "LA2",
    "JP1", "KR", "OC1", "SG2", "TW2", "VN2"
]

LEAGUE_QUEUE_TYPE_NAMES = {
    "RANKED_SOLO_5x5": "Ranked Solo/Duo",
    "RANKED_FLEX_SR": "Ranked Flex 5v5",
    "CHERRY": "Arena"
}

TFT_QUEUE_TYPE_NAMES = {
    "RANKED_TFT": "Ranked TFT",
}

# Platform mappings for Apex Legends
APEX_PLATFORM_MAPPING = {
    'Xbox': 'xbl',
    'Playstation': 'psn',
    'Origin (PC)': 'origin',
}

# Time mapping for Fortnite
FORTNITE_TIME_MAPPING = {
    'Season': 'season',
    'Lifetime': 'lifetime',
}

# Special emoji name mappings for League of Legends
SPECIAL_EMOJI_NAMES = {
    "Renata Glasc": "Renata",
    "Wukong": "MonkeyKing",
    "Miss Fortune": "MissFortune",
    "Xin Zhao": "XinZhao",
    "Aurelion Sol": "AurelionSol",
    "Bel'Veth": "Belveth",
    "Cho'Gath": "Chogath",
    "Nunu & Willump": "Nunu",
    "Lee Sin": "LeeSin",
    "K'Sante": "KSante",
    "Kog'Maw": "KogMaw",
    "Twisted Fate": "TwistedFate",
    "Dr. Mundo": "DrMundo",
    "Rek'Sai": "RekSai",
    "Kai'Sa": "KaiSa",
    "Vel'Koz": "Velkoz",
    "Kha'Zix": "Khazix",
    "Master Yi": "MasterYi",
}

# Latest bot updates
LATEST_UPDATES = (
    "**Version 2.3.0 (Truth or Dare!)**:\n\n"
    "**🎲 New Game Added!**\n"
    "- Play `/truthordare`! Choose SFW or NSFW, Truth or Dare, and face forfeits if you chicken out!"
)

SFW_TRUTHS = [
    "If you could have any superpower, what would it be and why?",
    "What's the most embarrassing thing that happened to you in school?",
    "What's a skill you wish you had?",
    "What's your guilty pleasure song or artist?",
    "If you could travel anywhere in the world right now, where would you go?",
    "What movie can you watch over and over again without getting tired of it?",
    "What's the weirdest food combination you genuinely enjoy?",
    "Who was your first celebrity crush?",
    "What's one thing you're really proud of accomplishing?",
    "If you were an animal, what would you be and why?",
    "What's the last book you read? Did you enjoy it?",
    "What is your biggest pet peeve?",
    "What's your favorite season and why?",
    "If you could meet any historical figure, who would it be?",
    "What's the strangest dream you've ever had?",
    "What hobby would you get into if time and money weren't an issue?",
    "What's your favorite type of weather?",
    "If you had to eat one meal for the rest of your life, what would it be?",
    "What was your favorite cartoon show as a kid?",
    "What's something you believed for way too long as a child?",
    "What's the best piece of advice you've ever received?",
    "Are you a morning person or a night owl?",
    "What's your go-to comfort food?",
    "If you could instantly learn any language, which one would you choose?",
    "What's the funniest joke you know by heart?",
    "What's something popular now that you just don't understand?",
    "Have you ever been told you look like a celebrity? Who?",
    "What's your favorite board game or card game?",
    "If you could eliminate one chore forever, what would it be?",
    "What's the most useless talent you have?",
    "What's your favorite holiday?",
    "What's a common misconception people have about you?",
    "If your pet could talk, what's the first question you'd ask it?",
    "What's the most memorable concert or live event you've attended?",
    "What's something you're currently learning or want to learn?",
    "What's your favorite way to relax?",
    "If you were stranded on a desert island, what three *non-essential* items would you want?",
    "What's the kindest thing someone has ever done for you?",
    "What fashion trend do you regret participating in?",
    "What fictional world would you love to live in?",
    "What's your biggest fear (that's relatively irrational)?",
    "What instrument do you wish you could play?",
    "What's the most interesting documentary you've watched?",
    "If you could switch lives with someone for a day, who would it be?",
    "What's your favorite pizza topping?",
    "What's something you're really bad at?",
    "What's the most beautiful place you've ever visited?",
    "What's your spirit animal?",
    "If you found a lottery ticket that won £10,000, what's the first thing you'd buy?",
    "What's a word you always misspell?",
    "What's your favorite type of dessert?",
    "Have you ever met someone famous?",
    "What's the best gift you've ever given or received?",
    "If you could invent anything, what problem would it solve?",
    "What topic could you give a 30-minute presentation on with no preparation?",
    "What's your favorite childhood memory?",
    "What's the silliest argument you've ever been in?",
    "If you had a warning label, what would it say?",
    "What song instantly puts you in a good mood?",
    "What's something you wish you were better at?",
    "What's the weirdest thing you've ever eaten?",
    "What's your dream job (even if it's unrealistic)?",
    "What do you procrastinate on the most?",
    "What's your favourite thing about where you live?",
    "If you could talk to your past self (age 15), what one piece of advice would you give?",
    "What's one small thing that makes your day better?",
    "What's the longest you've gone without sleep?",
    "If you could bring back one extinct animal, which would it be?",
    "What's a movie that made you cry?",
    "What's your favourite type of art (music, painting, literature, etc.)?",
    "What's something you learned recently that surprised you?",
    "What weird smell do you secretly like?",
    "What's the most adventurous thing you've ever done?",
    "If you were a ghost, who or where would you haunt?",
    "What's one rule you wish you could break without consequence?"
]
SFW_DARES = [
    "Do your best impression of a famous celebrity chosen by the group (use voice if possible, otherwise describe it).",
    "Talk in a funny accent (e.g., pirate, robot, posh) in voice chat until your next turn (or type 3 messages in that accent).",
    "Try to juggle 3 safe items you have nearby (like socks or small fruit) for 15 seconds. Report your success.",
    "Do 10 real push-ups or 20 jumping jacks right now. Confirm when done.",
    "Sing the chorus of your favorite song out loud (use voice if possible).",
    "Wear socks on your hands for the next 10 minutes.",
    "Try to lick your elbow. Report if you succeeded.",
    "Speak only in rhymes for the next 3 messages you send.",
    "Make up a short rap about someone else in the chat and say it/type it.",
    "Balance a spoon on your nose for 10 seconds. Report success.",
    "Act like a cat until your next turn (meow in voice, or use cat-like typing).",
    "Tell a cheesy joke. If no one laughs (reacts), tell another one.",
    "Make the ugliest face you possibly can (show on camera if possible, otherwise describe it).",
    "Let the group choose a funny (SFW) word. Work it into your next 3 spoken/typed sentences naturally.",
    "Do your best chicken dance for 15 seconds. Confirm when done.",
    "Pretend to be a statue for 1 minute – no moving, typing, or reacting! Confirm when done.",
    "Try to pat your head and rub your stomach at the same time for 10 seconds. Report success.",
    "Blindfolded, have someone nearby hand you an object. Guess it by touch in 3 tries.",
    "Give a dramatic reading of a random paragraph from a physical book or webpage you have open.",
    "Build a small tower (at least 3 items high) out of objects on your desk in 60 seconds. Send a picture or describe it.",
    "Try to say the alphabet backward out loud as fast as you can.",
    "Draw a picture of another user's avatar using pen and paper with your non-dominant hand. Send a picture.",
    "Do an impression of another player (voice or text) until someone guesses who it is.",
    "Invent a new, silly handshake and teach it to someone nearby (or describe it).",
    "Wear an item of clothing backward until your next turn.",
    "Pretend you are a news reporter reporting live from your room.",
    "Try to touch your nose with your tongue. Report success.",
    "Make up a short story, but each word must start with the same letter (say or type it).",
    "Hop on one foot for 30 seconds. Confirm when done.",
    "Let someone else style your hair messily (if possible). Send a picture or describe.",
    "Act out a scene from your favorite movie (use voice/camera if possible).",
    "Try to whistle a song chosen by the group.",
    "Do your best runway model walk across your room. Confirm when done.",
    "Pretend to be a flight attendant giving safety instructions for your chair.",
    "Speak like Yoda for your next 3 messages/sentences.",
    "Try to fold a piece of paper more than 7 times.",
    "Tell the group your most embarrassing autocorrect fail.",
    "Make 3 different animal noises chosen by the group (use voice if possible).",
    "Act like a T-Rex (short arms, stomp feet) for 30 seconds. Confirm when done.",
    "Give a genuine compliment to everyone currently active in chat/voice.",
    "Spin around 5 times and then try to walk in a straight line. Report success.",
    "Wear a funny hat (or make one out of paper) for the next 10 minutes. Send a picture.",
    "Let someone draw a (washable) mustache on your face. Send a picture.",
    "Moonwalk across your room. Confirm when done.",
    "Recite a nursery rhyme in a scary voice (use voice if possible).",
    "Try to make someone else in the group laugh without touching them or talking (use camera/gestures if possible).",
    "Eat a spoonful of a weird (but safe!) food combination you can make right now (e.g., peanut butter and pickles). Describe the taste.",
    "Put an ice cube down your shirt/back and keep it there for 30 seconds.",
    "Try to write your name in the air using your foot.",
    "Act out your favorite emoji physically.",
    "Go outside (or to a window) and yell 'I love [Something silly]!' at the top of your lungs.",
    "Make a funny face and hold it for 1 minute (show on cam if possible).",
    "Text a friend 'Did you see that purple squirrel?' and show the response (blur name).",
    "Pretend to be an old person complaining about something near you.",
    "Try to name 5 countries starting with the letter 'P' in 15 seconds out loud.",
    "Wear your trousers/shorts/skirt on your head like a hat for 5 minutes. Send pic.",
    "Do 10 air squats right now.",
    "Try to mimic the voice of another player (if in voice).",
    "Let someone tickle you for 20 seconds (if someone is nearby!).",
    "Describe what you had for breakfast, but make it sound incredibly dramatic.",
    "Act like you are secretly a spy communicating via gestures or coded words.",
    "Try to lick your own nose. Report success.",
    "Build a mini fort using pillows/blankets near you.",
    "Make up a theme song for yourself and sing/say it.",
    "Tell a short story using only physical gestures (show on cam if possible).",
    "Try to keep a straight face while everyone else tries to make you laugh for 1 minute (show on cam if possible).",
    "Do an impression of a cartoon character (voice if possible).",
    "Walk backward around your room once.",
    "Pretend your arms are noodles for the next minute.",
    "Try to say 'Red lorry, yellow lorry' five times fast out loud.",
    "Invent a secret handshake with someone nearby (or describe one).",
    "Act like a dog playing fetch for 30 seconds.",
    "Try to solve a simple math problem (like 17x6) out loud without a calculator.",
    "Give yourself a funny nickname and introduce yourself with it until your next turn.",
    "Use finger puppets (just your fingers) to act out a short scene (show on cam if possible)."
]
NSFW_TRUTHS = [
    "What's the biggest secret you've kept from a partner?",
    "What's your 'type' physically?",
    "Have you ever skinny-dipped? Where and with whom?",
    "What's the most embarrassing thing you've searched for online?",
    "Describe your most awkward date.",
    "What's one thing you find attractive that most people might not?",
    "Have you ever used a dating app? Which one and what was your best/worst experience?",
    "What's a fantasy you've never told anyone?",
    "What's the naughtiest thing you've done in public?",
    "How important is physical intimacy to you in a relationship (scale of 1-10)?",
    "Have you ever been caught doing something intimate?",
    "What's the longest you've gone without sex?",
    "What's your biggest turn-on?",
    "What's your biggest turn-off?",
    "Have you ever faked an orgasm?",
    "What's the weirdest place you've ever hooked up with someone?",
    "Do you have any fetishes? What are they?",
    "What's something you're self-conscious about regarding your body?",
    "Have you ever had a one-night stand? Regret it?",
    "What's the most scandalous photo or video on your phone right now?",
    "Have you ever sent nudes? To whom?",
    "What's your 'number' (number of partners)?",
    "What do you think about friends with benefits?",
    "Have you ever cheated on a partner (emotionally or physically)?",
    "Have you ever been cheated on?",
    "What's the most adventurous thing you've done in the bedroom?",
    "Do you prefer giving or receiving?",
    "What's something you find surprisingly sexy?",
    "Have you ever watched porn with a partner?",
    "What's your opinion on public displays of affection?",
    "What's the kinkiest thing you're willing to admit to trying?",
    "Have you ever lied about your sexual history?",
    "What's your favorite part of your own body?",
    "What's your favorite part of a potential partner's body?",
    "Have you ever had a crush on a friend's partner?",
    "What's the worst thing someone has said to you during/after sex?",
    "What's the best compliment someone has given you during/after sex?",
    "Do you prefer morning sex or night sex?",
    "What's your go-to move to initiate intimacy?",
    "Have you ever used sex toys? Which ones?",
    "What's the most embarrassing noise you've made during sex?",
    "Have you ever stalked an ex or crush on social media?",
    "What's the minimum amount of time you need to know someone before sleeping with them?",
    "What's your opinion on sexting?",
    "Have you ever fantasized about someone in this room/group?",
    "What's the biggest romantic risk you've ever taken?",
    "What's your favourite position?",
    "Have you ever done 'the walk of shame'?",
    "What's the most disappointing sexual experience you've had?",
    "What song gets you in the mood?",
    "Have you ever been caught masturbating?",
    "What's your biggest insecurity in a relationship?",
    "What physical feature do you find most attractive?",
    "Have you ever paid for sex or been paid for sex?",
    "What's the most intimate thing you've done with someone non-sexually?",
    "What's your 'hall pass' celebrity?",
    "Would you rather have amazing sex or an amazing meal?",
    "Have you ever lied to get out of sex?",
    "What's the strangest thing that turns you on?",
    "Have you ever role-played in the bedroom?",
    "What's your favorite lingerie or type of underwear (on yourself or partner)?",
    "Have you ever had sex outdoors?",
    "What's the most public place you've fooled around?",
    "What's something you wish your partner (current or past) did more/less of?",
    "Have you ever regretted sleeping with someone?",
    "What's the biggest age gap you'd be comfortable with in a partner?",
    "Have you ever considered an open relationship?",
    "What's the first thing you notice attractive about someone?",
    "Have you ever had a threesome or considered one?",
    "What's the most inappropriate time you've felt aroused?",
    "Do you believe in love at first sight?",
    "What's your definition of 'cheating'?",
    "Have you ever had a sex dream about someone unexpected?",
    "What's the most overrated sexual act, in your opinion?",
    "What's one question you hope you don't get asked?"
]
NSFW_DARES = [
    "Send a flirty text to the last person you messaged (blur name!) and show the group.",
    "Describe your ideal romantic/intimate evening in sensual detail (voice or text).",
    "Remove one item of clothing (your choice, within comfort). Confirm when done.",
    "Let someone in the group suggest where to draw a (non-permanent) suggestive shape on your arm/leg. Send pic.",
    "Give a seductive explanation (voice or text) of how to make toast or tie shoelaces.",
    "Whisper a secret desire or fantasy into the mic (or DM someone if not in voice).",
    "Do a 'sexy' dance for 30 seconds (camera on if comfortable, otherwise confirm completion).",
    "Lick whipped cream, honey, or chocolate sauce off your own finger/hand seductively (camera on if comfortable).",
    "Read the last R-rated text message you sent or received out loud (omit names).",
    "Swap one item of clothing with someone nearby for the next round (if possible).",
    "Take a 'body shot' off yourself (lick salt, take shot/drink, suck lime) - e.g., from your arm.",
    "Give a sensual massage (shoulder, neck, hand) to yourself or someone nearby for 1 minute.",
    "Post an old, embarrassing (but SFW) picture of yourself to the chat.",
    "Show the group the most suggestive *SFW* photo on your phone (can be art, meme, etc.).",
    "Write a short, steamy sentence about the person to your left (or previous chatter) on paper and show it.",
    "Re-enact your first kiss (with a pillow or your hand).",
    "Let someone lightly spank you (if someone is nearby and consents!).",
    "Remove your socks using only your teeth.",
    "Try to seduce an inanimate object near you (like a lamp or chair) for 1 minute (voice/camera if possible).",
    "Send a voice note to someone (outside the game, with permission) saying 'I miss you' in your most seductive voice.",
    "Let the group pick a dare for you from a list of 3 *real-life* options you provide.",
    "Take off your shirt/top for the next round (wear bra/undershirt if applicable). Confirm when done.",
    "Describe your perfect partner using only suggestive adjectives (voice or text).",
    "Truth or Dare? If you pick Dare again, you have to do *two* dares next time.",
    "Give someone nearby (or a pillow) a lap dance (can be silly or serious) for 30 seconds.",
    "Show the group your phone's *photo gallery thumbnail view* for 5 seconds (careful!).",
    "Let someone suggest a word to write on your stomach/back with a washable marker (show pic if comfortable).",
    "Eat a piece of fruit (like a banana or strawberry) in the most provocative way possible (camera on if comfortable).",
    "Make 'bedroom eyes' at the camera or describe them for a full minute.",
    "Call a friend and pretend you're breaking up with them (then reveal it's a dare!).",
    "Apply lipstick/chapstick without using a mirror. Send a picture.",
    "Let someone blindfold you and feed you a common food item (if possible). Guess what it is.",
    "Do your best 'orgasm face' (camera on if comfortable).",
    "Go into another room, take a slightly suggestive selfie (SFW, face/shoulders up), and send it to the group.",
    "Tell a dirty joke (voice or text).",
    "Remove your trousers/skirt/shorts for the rest of the game (wear underwear!). Confirm when done.",
    "Act out your favorite sex position using only your hands (camera on if comfortable).",
    "Let someone pour a cup of cold water on your feet.",
    "Serenade someone in the group with a love song (voice or text).",
    "Stick out your tongue and let someone nearby place a piece of candy or fruit on it (if possible).",
    "Let the group look through your music playlist history for 1 minute (share screen?).",
    "Slowly lick a lollipop or ice cream cone (camera on if comfortable).",
    "Text your crush or partner 'What are you wearing?' right now. Share response if comfortable.",
    "Put on blindfold, spin around, and kiss the first object/wall you touch.",
    "Let someone else choose who you have to blow a kiss to (camera on if possible).",
    "Give yourself or someone nearby a hickey (requires consent!).",
    "Pretend to orgasm loudly (use voice if possible).",
    "Let someone nearby sniff your neck or hair (if possible and consent given).",
    "Take a shot of a safe drink (juice, water, soda - or alcohol if applicable/legal/safe).",
    "Wear an item of clothing as underwear (e.g., sock in bra/pants) for the next round.",
    "Slow dance by yourself or with someone nearby for one song.",
    "Let someone put lipstick on you while you're blindfolded (if possible). Send pic.",
    "Make loud slurping noises while drinking something.",
    "Confess your kinkiest thought right now (voice or text).",
    "Let someone tie your hands loosely behind your back with a scarf for 5 minutes (if possible).",
    "Take a bite out of a raw onion or lemon wedge. Describe reaction.",
    "Show the group your 'O' face (camera on if comfortable).",
    "Write a sexy poem about an object in your room and read/show it.",
    "Let someone DM you something naughty (SFW text only) and read it aloud dramatically.",
    "Do a strip tease removing only one agreed-upon item (e.g., hat, sock, glove).",
    "Make out with your own hand for 15 seconds.",
    "Try to remove your own bra/shirt with only one hand.",
    "Let the group post a harmlessly embarrassing status update on one of your social media accounts (you type it).",
    "Massage your own feet for 1 minute.",
    "Stick your finger in your own ear gently.",
    "Blindfold yourself and guess who is talking based on their voice (if in voice chat).",
    "Let someone nearby pour a little bit of their drink into your mouth (if possible/safe).",
    "Describe your ideal foreplay scenario (voice or text).",
    "Let someone take a picture of your feet and post it in chat.",
    "Kiss someone/something nearby passionately for 15 seconds.",
    "Speak only in questions until your next turn.",
    "Let someone nearby tickle you until you beg them to stop (if possible).",
    "Put on lipstick/chapstick and kiss a piece of paper, then show it.",
    "Do 10 'sexy' pushups (describe or show on cam).",
    "Tell the group the dirtiest word you know (voice or text, within TOS)."
]

# Forfeits for not completing a dare
FORFEITS = [
    "Tell the group an embarrassing (but SFW) story about yourself.",
    "Let the group choose a funny (SFW) nickname for you for the next hour.",
    "Post \"I forfeited a dare!\" in the chat.",
    "Do 5 push-ups (or another simple exercise) right now.",
    "Compliment the person who dared you.",
    "Speak in a silly voice until your next turn.",
    "Change your profile picture to something silly (chosen by the group?) for 10 minutes.",
    "Tell a dad joke.",
    "Try to lick your nose.",
    "Let someone else ask you a SFW Truth question."
]