# League related constants
LEAGUE_REGIONS = [
    "EUW1", "EUN1", "TR1", "RU", "NA1", "BR1", "LA1", "LA2",
    "JP1", "KR", "OC1", "SG2", "TW2", "VN2"
]

LEAGUE_QUEUE_TYPE_NAMES = {
    "RANKED_SOLO_5x5": "Ranked Solo/Duo",
    "RANKED_FLEX_SR": "Ranked Flex 5v5",
    "CHERRY": "Arena",
    "KIWI": "ARAM Mayhem"
}

TFT_QUEUE_TYPE_NAMES = {
    "RANKED_TFT": "Ranked TFT",
}

# Region to routing cluster mapping for match history endpoints
REGION_TO_ROUTING = {
    "NA1": "americas", "BR1": "americas", "LA1": "americas", "LA2": "americas",
    "EUW1": "europe", "EUN1": "europe", "TR1": "europe", "RU": "europe",
    "JP1": "asia", "KR": "asia",
    "OC1": "sea", "SG2": "sea", "TW2": "sea", "VN2": "sea"
}

# Platform mappings for Apex Legends
APEX_PLATFORM_MAPPING = {
    'Xbox': 'xbl',
    'Playstation': 'psn',
    'Origin (PC)': 'origin',
}

# Time mapping for Fortnite
FORTNITE_TIME_MAPPING = {
    'Season': 'season',
    'Lifetime': 'lifetime',
}

# Special emoji name mappings for League of Legends
SPECIAL_EMOJI_NAMES = {
    "Renata Glasc": "Renata",
    "Wukong": "MonkeyKing",
    "Miss Fortune": "MissFortune",
    "Xin Zhao": "XinZhao",
    "Aurelion Sol": "AurelionSol",
    "Bel'Veth": "Belveth",
    "Cho'Gath": "Chogath",
    "Nunu & Willump": "Nunu",
    "Lee Sin": "LeeSin",
    "K'Sante": "KSante",
    "Kog'Maw": "KogMaw",
    "Twisted Fate": "TwistedFate",
    "Dr. Mundo": "DrMundo",
    "Rek'Sai": "RekSai",
    "Kai'Sa": "KaiSa",
    "Vel'Koz": "Velkoz",
    "Kha'Zix": "Khazix",
    "Master Yi": "MasterYi",
}

# Latest bot updates

LATEST_UPDATES = (
    "## 🚀 Version 2.11.1\n\n"
    "### 🌌 League Cog Fixes\n\n"
    "**Stability Updates**\n"
    "• **League Profile**: Fixed a bug where viewing a profile for too long could cause an 'Invalid Webhook Token' error. The view now times out gracefully after 14 minutes.\n\n"
    "### 🌌 New Features: Cosmos\n\n"
    "**Space Commands**\n"
    "• **/apod**: Astronomy Picture of the Day from NASA\n"
    "• **/iss**: Real-time location of the International Space Station\n"
    "• **/people**: List of humans currently in space\n"
    "• **/launch**: Information on the next upcoming rocket launch\n\n"
    "Visit [astrostats.info](https://astrostats.info) for more information."
)

SFW_TRUTHS = [
    "If you could have any superpower, what would it be and why?",
    "What's the most embarrassing thing that happened to you in school?",
    "What's a skill you wish you had?",
    "What's your guilty pleasure song or artist?",
    "If you could travel anywhere in the world right now, where would you go?",
    "What movie can you watch over and over again without getting tired of it?",
    "What's the weirdest food combination you genuinely enjoy?",
    "Who was your first celebrity crush?",
    "What's one thing you're really proud of accomplishing?",
    "If you were an animal, what would you be and why?",
    "What's the last book you read? Did you enjoy it?",
    "What is your biggest pet peeve?",
    "What's your favorite season and why?",
    "If you could meet any historical figure, who would it be?",
    "What's the strangest dream you've ever had?",
    "What hobby would you get into if time and money weren't an issue?",
    "What's your favorite type of weather?",
    "If you had to eat one meal for the rest of your life, what would it be?",
    "What was your favorite cartoon show as a kid?",
    "What's something you believed for way too long as a child?",
    "What's the best piece of advice you've ever received?",
    "Are you a morning person or a night owl?",
    "What's your go-to comfort food?",
    "If you could instantly learn any language, which one would you choose?",
    "What's the funniest joke you know by heart?",
    "What's something popular now that you just don't understand?",
    "Have you ever been told you look like a celebrity? Who?",
    "What's your favorite board game or card game?",
    "If you could eliminate one chore forever, what would it be?",
    "What's the most useless talent you have?",
    "What's your favorite holiday?",
    "What's a common misconception people have about you?",
    "If your pet could talk, what's the first question you'd ask it?",
    "What's the most memorable concert or live event you've attended?",
    "What's something you're currently learning or want to learn?",
    "What's your favorite way to relax?",
    "If you were stranded on a desert island, what three *non-essential* items would you want?",
    "What's the kindest thing someone has ever done for you?",
    "What fashion trend do you regret participating in?",
    "What fictional world would you love to live in?",
    "What's your biggest fear (that's relatively irrational)?",
    "What instrument do you wish you could play?",
    "What's the most interesting documentary you've watched?",
    "If you could switch lives with someone for a day, who would it be?",
    "What's your favorite pizza topping?",
    "What's something you're really bad at?",
    "What's the most beautiful place you've ever visited?",
    "What's your spirit animal?",
    "If you found a lottery ticket that won £10,000, what's the first thing you'd buy?",
    "What's a word you always misspell?",
    "What's your favorite type of dessert?",
    "Have you ever met someone famous?",
    "What's the best gift you've ever given or received?",
    "If you could invent anything, what problem would it solve?",
    "What topic could you give a 30-minute presentation on with no preparation?",
    "What's your favorite childhood memory?",
    "What's the silliest argument you've ever been in?",
    "If you had a warning label, what would it say?",
    "What song instantly puts you in a good mood?",
    "What's something you wish you were better at?",
    "What's the weirdest thing you've ever eaten?",
    "What's your dream job (even if it's unrealistic)?",
    "What do you procrastinate on the most?",
    "What's your favourite thing about where you live?",
    "If you could talk to your past self (age 15), what one piece of advice would you give?",
    "What's one small thing that makes your day better?",
    "What's the longest you've gone without sleep?",
    "If you could bring back one extinct animal, which would it be?",
    "What's a movie that made you cry?",
    "What's your favourite type of art (music, painting, literature, etc.)?",
    "What's something you learned recently that surprised you?",
    "What weird smell do you secretly like?",
    "What's the most adventurous thing you've ever done?",
    "If you were a ghost, who or where would you haunt?",
    "What's one rule you wish you could break without consequence?"
]
SFW_DARES = [
    "Do your best impression of a famous celebrity chosen by the group (use voice if possible, otherwise describe it).",
    "Talk in a funny accent (e.g., pirate, robot, posh) in voice chat until your next turn (or type 3 messages in that accent).",
    "Try to juggle 3 safe items you have nearby (like socks or small fruit) for 15 seconds. Report your success.",
    "Do 10 real push-ups or 20 jumping jacks right now. Confirm when done.",
    "Sing the chorus of your favorite song out loud (use voice if possible).",
    "Wear socks on your hands for the next 10 minutes.",
    "Try to lick your elbow. Report if you succeeded.",
    "Speak only in rhymes for the next 3 messages you send.",
    "Make up a short rap about someone else in the chat and say it/type it.",
    "Balance a spoon on your nose for 10 seconds. Report success.",
    "Act like a cat until your next turn (meow in voice, or use cat-like typing).",
    "Tell a cheesy joke. If no one laughs (reacts), tell another one.",
    "Make the ugliest face you possibly can (show on camera if possible, otherwise describe it).",
    "Let the group choose a funny (SFW) word. Work it into your next 3 spoken/typed sentences naturally.",
    "Do your best chicken dance for 15 seconds. Confirm when done.",
    "Pretend to be a statue for 1 minute – no moving, typing, or reacting! Confirm when done.",
    "Try to pat your head and rub your stomach at the same time for 10 seconds. Report success.",
    "Blindfolded, have someone nearby hand you an object. Guess it by touch in 3 tries.",
    "Give a dramatic reading of a random paragraph from a physical book or webpage you have open.",
    "Build a small tower (at least 3 items high) out of objects on your desk in 60 seconds. Send a picture or describe it.",
    "Try to say the alphabet backward out loud as fast as you can.",
    "Draw a picture of another user's avatar using pen and paper with your non-dominant hand. Send a picture.",
    "Do an impression of another player (voice or text) until someone guesses who it is.",
    "Invent a new, silly handshake and teach it to someone nearby (or describe it).",
    "Wear an item of clothing backward until your next turn.",
    "Pretend you are a news reporter reporting live from your room.",
    "Try to touch your nose with your tongue. Report success.",
    "Make up a short story, but each word must start with the same letter (say or type it).",
    "Hop on one foot for 30 seconds. Confirm when done.",
    "Let someone else style your hair messily (if possible). Send a picture or describe.",
    "Act out a scene from your favorite movie (use voice/camera if possible).",
    "Try to whistle a song chosen by the group.",
    "Do your best runway model walk across your room. Confirm when done.",
    "Pretend to be a flight attendant giving safety instructions for your chair.",
    "Speak like Yoda for your next 3 messages/sentences.",
    "Try to fold a piece of paper more than 7 times.",
    "Tell the group your most embarrassing autocorrect fail.",
    "Make 3 different animal noises chosen by the group (use voice if possible).",
    "Act like a T-Rex (short arms, stomp feet) for 30 seconds. Confirm when done.",
    "Give a genuine compliment to everyone currently active in chat/voice.",
    "Spin around 5 times and then try to walk in a straight line. Report success.",
    "Wear a funny hat (or make one out of paper) for the next 10 minutes. Send a picture.",
    "Let someone draw a (washable) mustache on your face. Send a picture.",
    "Moonwalk across your room. Confirm when done.",
    "Recite a nursery rhyme in a scary voice (use voice if possible).",
    "Try to make someone else in the group laugh without touching them or talking (use camera/gestures if possible).",
    "Eat a spoonful of a weird (but safe!) food combination you can make right now (e.g., peanut butter and pickles). Describe the taste.",
    "Put an ice cube down your shirt/back and keep it there for 30 seconds.",
    "Try to write your name in the air using your foot.",
    "Act out your favorite emoji physically.",
    "Go outside (or to a window) and yell 'I love [Something silly]!' at the top of your lungs.",
    "Make a funny face and hold it for 1 minute (show on cam if possible).",
    "Text a friend 'Did you see that purple squirrel?' and show the response (blur name).",
    "Pretend to be an old person complaining about something near you.",
    "Try to name 5 countries starting with the letter 'P' in 15 seconds out loud.",
    "Wear your trousers/shorts/skirt on your head like a hat for 5 minutes. Send pic.",
    "Do 10 air squats right now.",
    "Try to mimic the voice of another player (if in voice).",
    "Let someone tickle you for 20 seconds (if someone is nearby!).",
    "Describe what you had for breakfast, but make it sound incredibly dramatic.",
    "Act like you are secretly a spy communicating via gestures or coded words.",
    "Try to lick your own nose. Report success.",
    "Build a mini fort using pillows/blankets near you.",
    "Make up a theme song for yourself and sing/say it.",
    "Tell a short story using only physical gestures (show on cam if possible).",
    "Try to keep a straight face while everyone else tries to make you laugh for 1 minute (show on cam if possible).",
    "Do an impression of a cartoon character (voice if possible).",
    "Walk backward around your room once.",
    "Pretend your arms are noodles for the next minute.",
    "Try to say 'Red lorry, yellow lorry' five times fast out loud.",
    "Invent a secret handshake with someone nearby (or describe one).",
    "Act like a dog playing fetch for 30 seconds.",
    "Try to solve a simple math problem (like 17x6) out loud without a calculator.",
    "Give yourself a funny nickname and introduce yourself with it until your next turn.",
    "Use finger puppets (just your fingers) to act out a short scene (show on cam if possible)."
]
NSFW_TRUTHS = [
    "What's the biggest secret you've kept from a partner?",
    "What's your 'type' physically?",
    "Have you ever skinny-dipped? Where and with whom?",
    "What's the most embarrassing thing you've searched for online?",
    "Describe your most awkward date.",
    "What's one thing you find attractive that most people might not?",
    "Have you ever used a dating app? Which one and what was your best/worst experience?",
    "What's a fantasy you've never told anyone?",
    "What's the naughtiest thing you've done in public?",
    "How important is physical intimacy to you in a relationship (scale of 1-10)?",
    "Have you ever been caught doing something intimate?",
    "What's the longest you've gone without sex?",
    "What's your biggest turn-on?",
    "What's your biggest turn-off?",
    "Have you ever faked an orgasm?",
    "What's the weirdest place you've ever hooked up with someone?",
    "Do you have any fetishes? What are they?",
    "What's something you're self-conscious about regarding your body?",
    "Have you ever had a one-night stand? Regret it?",
    "What's the most scandalous photo or video on your phone right now?",
    "Have you ever sent nudes? To whom?",
    "What's your 'number' (number of partners)?",
    "What do you think about friends with benefits?",
    "Have you ever cheated on a partner (emotionally or physically)?",
    "Have you ever been cheated on?",
    "What's the most adventurous thing you've done in the bedroom?",
    "Do you prefer giving or receiving?",
    "What's something you find surprisingly sexy?",
    "Have you ever watched porn with a partner?",
    "What's your opinion on public displays of affection?",
    "What's the kinkiest thing you're willing to admit to trying?",
    "Have you ever lied about your sexual history?",
    "What's your favorite part of your own body?",
    "What's your favorite part of a potential partner's body?",
    "Have you ever had a crush on a friend's partner?",
    "What's the worst thing someone has said to you during/after sex?",
    "What's the best compliment someone has given you during/after sex?",
    "Do you prefer morning sex or night sex?",
    "What's your go-to move to initiate intimacy?",
    "Have you ever used sex toys? Which ones?",
    "What's the most embarrassing noise you've made during sex?",
    "Have you ever stalked an ex or crush on social media?",
    "What's the minimum amount of time you need to know someone before sleeping with them?",
    "What's your opinion on sexting?",
    "Have you ever fantasized about someone in this room/group?",
    "What's the biggest romantic risk you've ever taken?",
    "What's your favourite position?",
    "Have you ever done 'the walk of shame'?",
    "What's the most disappointing sexual experience you've had?",
    "What song gets you in the mood?",
    "Have you ever been caught masturbating?",
    "What's your biggest insecurity in a relationship?",
    "What physical feature do you find most attractive?",
    "Have you ever paid for sex or been paid for sex?",
    "What's the most intimate thing you've done with someone non-sexually?",
    "What's your 'hall pass' celebrity?",
    "Would you rather have amazing sex or an amazing meal?",
    "Have you ever lied to get out of sex?",
    "What's the strangest thing that turns you on?",
    "Have you ever role-played in the bedroom?",
    "What's your favorite lingerie or type of underwear (on yourself or partner)?",
    "Have you ever had sex outdoors?",
    "What's the most public place you've fooled around?",
    "What's something you wish your partner (current or past) did more/less of?",
    "Have you ever regretted sleeping with someone?",
    "What's the biggest age gap you'd be comfortable with in a partner?",
    "Have you ever considered an open relationship?",
    "What's the first thing you notice attractive about someone?",
    "Have you ever had a threesome or considered one?",
    "What's the most inappropriate time you've felt aroused?",
    "Do you believe in love at first sight?",
    "What's your definition of 'cheating'?",
    "Have you ever had a sex dream about someone unexpected?",
    "What's the most overrated sexual act, in your opinion?",
    "What's one question you hope you don't get asked?"
]
NSFW_DARES = [
    "Send a flirty text to the last person you messaged (blur name!) and show the group.",
    "Describe your ideal romantic/intimate evening in sensual detail (voice or text).",
    "Remove one item of clothing (your choice, within comfort). Confirm when done.",
    "Let someone in the group suggest where to draw a (non-permanent) suggestive shape on your arm/leg. Send pic.",
    "Give a seductive explanation (voice or text) of how to make toast or tie shoelaces.",
    "Whisper a secret desire or fantasy into the mic (or DM someone if not in voice).",
    "Do a 'sexy' dance for 30 seconds (camera on if comfortable, otherwise confirm completion).",
    "Lick whipped cream, honey, or chocolate sauce off your own finger/hand seductively (camera on if comfortable).",
    "Read the last R-rated text message you sent or received out loud (omit names).",
    "Swap one item of clothing with someone nearby for the next round (if possible).",
    "Take a 'body shot' off yourself (lick salt, take shot/drink, suck lime) - e.g., from your arm.",
    "Give a sensual massage (shoulder, neck, hand) to yourself or someone nearby for 1 minute.",
    "Post an old, embarrassing (but SFW) picture of yourself to the chat.",
    "Show the group the most suggestive *SFW* photo on your phone (can be art, meme, etc.).",
    "Write a short, steamy sentence about the person to your left (or previous chatter) on paper and show it.",
    "Re-enact your first kiss (with a pillow or your hand).",
    "Let someone lightly spank you (if someone is nearby and consents!).",
    "Remove your socks using only your teeth.",
    "Try to seduce an inanimate object near you (like a lamp or chair) for 1 minute (voice/camera if possible).",
    "Send a voice note to someone (outside the game, with permission) saying 'I miss you' in your most seductive voice.",
    "Let the group pick a dare for you from a list of 3 *real-life* options you provide.",
    "Take off your shirt/top for the next round (wear bra/undershirt if applicable). Confirm when done.",
    "Describe your perfect partner using only suggestive adjectives (voice or text).",
    "Truth or Dare? If you pick Dare again, you have to do *two* dares next time.",
    "Give someone nearby (or a pillow) a lap dance (can be silly or serious) for 30 seconds.",
    "Show the group your phone's *photo gallery thumbnail view* for 5 seconds (careful!).",
    "Let someone suggest a word to write on your stomach/back with a washable marker (show pic if comfortable).",
    "Eat a piece of fruit (like a banana or strawberry) in the most provocative way possible (camera on if comfortable).",
    "Make 'bedroom eyes' at the camera or describe them for a full minute.",
    "Call a friend and pretend you're breaking up with them (then reveal it's a dare!).",
    "Apply lipstick/chapstick without using a mirror. Send a picture.",
    "Let someone blindfold you and feed you a common food item (if possible). Guess what it is.",
    "Do your best 'orgasm face' (camera on if comfortable).",
    "Go into another room, take a slightly suggestive selfie (SFW, face/shoulders up), and send it to the group.",
    "Tell a dirty joke (voice or text).",
    "Remove your trousers/skirt/shorts for the rest of the game (wear underwear!). Confirm when done.",
    "Act out your favorite sex position using only your hands (camera on if comfortable).",
    "Let someone pour a cup of cold water on your feet.",
    "Serenade someone in the group with a love song (voice or text).",
    "Stick out your tongue and let someone nearby place a piece of candy or fruit on it (if possible).",
    "Let the group look through your music playlist history for 1 minute (share screen?).",
    "Slowly lick a lollipop or ice cream cone (camera on if comfortable).",
    "Text your crush or partner 'What are you wearing?' right now. Share response if comfortable.",
    "Put on blindfold, spin around, and kiss the first object/wall you touch.",
    "Let someone else choose who you have to blow a kiss to (camera on if possible).",
    "Give yourself or someone nearby a hickey (requires consent!).",
    "Pretend to orgasm loudly (use voice if possible).",
    "Let someone nearby sniff your neck or hair (if possible and consent given).",
    "Take a shot of a safe drink (juice, water, soda - or alcohol if applicable/legal/safe).",
    "Wear an item of clothing as underwear (e.g., sock in bra/pants) for the next round.",
    "Slow dance by yourself or with someone nearby for one song.",
    "Let someone put lipstick on you while you're blindfolded (if possible). Send pic.",
    "Make loud slurping noises while drinking something.",
    "Confess your kinkiest thought right now (voice or text).",
    "Let someone tie your hands loosely behind your back with a scarf for 5 minutes (if possible).",
    "Take a bite out of a raw onion or lemon wedge. Describe reaction.",
    "Show the group your 'O' face (camera on if comfortable).",
    "Write a sexy poem about an object in your room and read/show it.",
    "Let someone DM you something naughty (SFW text only) and read it aloud dramatically.",
    "Do a strip tease removing only one agreed-upon item (e.g., hat, sock, glove).",
    "Make out with your own hand for 15 seconds.",
    "Try to remove your own bra/shirt with only one hand.",
    "Let the group post a harmlessly embarrassing status update on one of your social media accounts (you type it).",
    "Massage your own feet for 1 minute.",
    "Stick your finger in your own ear gently.",
    "Blindfold yourself and guess who is talking based on their voice (if in voice chat).",
    "Let someone nearby pour a little bit of their drink into your mouth (if possible/safe).",
    "Describe your ideal foreplay scenario (voice or text).",
    "Let someone take a picture of your feet and post it in chat.",
    "Kiss someone/something nearby passionately for 15 seconds.",
    "Speak only in questions until your next turn.",
    "Let someone nearby tickle you until you beg them to stop (if possible).",
    "Put on lipstick/chapstick and kiss a piece of paper, then show it.",
    "Do 10 'sexy' pushups (describe or show on cam).",
    "Tell the group the dirtiest word you know (voice or text, within TOS)."
]

# Would You Rather questions
SFW_WOULD_YOU_RATHER = [
    # --- Superpowers & Abilities ---
    "Would you rather have the ability to fly or be invisible?",
    "Would you rather have the power to read minds or the power to see the future?",
    "Would you rather be able to breathe underwater or survive in outer space without a suit?",
    "Would you rather have super strength or super speed?",
    "Would you rather be able to speak every language fluently or play every instrument perfectly?",
    "Would you rather have a rewind button for your life or a pause button?",
    "Would you rather never need to sleep or never need to eat?",
    "Would you rather be able to teleport anywhere or time travel to the past?",
    "Would you rather be able to talk to animals or speak to the dead?",
    "Would you rather have night vision or X-ray vision?",
    "Would you rather possess telekinesis or telepathy?",
    "Would you rather control fire or control water?",
    "Would you rather have a photographic memory or be able to forget anything you want?",
    "Would you rather be the smartest person in the world or the strongest?",
    "Would you rather never get sick or never get injured?",
    "Would you rather be able to change your appearance at will or change your voice at will?",
    "Would you rather stop time for 10 seconds every day or rewind time for 10 seconds every day?",
    "Would you rather know the history of every object you touch or know the future of every person you touch?",
    "Would you rather possess the ability to fly at 10 mph or run at 100 mph?",
    "Would you rather have a personal theme song that plays when you enter a room or a movie montage whenever you do something boring?",
    "Would you rather be able to run as fast as a cheetah or swim as fast as a dolphin?",
    "Would you rather always know when someone is lying or always get away with lying?",
    "Would you rather have eyes in the back of your head or 360-degree hearing?",
    "Would you rather be invisible to computers or invisible to people?",
    "Would you rather have the ability to shrink down to the size of an ant or grow to the size of a building?",

    # --- Time & History ---
    "Would you rather live in the distant past or the distant future?",
    "Would you rather witness the beginning of the universe or the end of the world?",
    "Would you rather meet your ancestors or your great-great-grandchildren?",
    "Would you rather be a famous historical figure or a famous celebrity today?",
    "Would you rather relive your favorite memory or erase your worst memory?",
    "Would you rather live in the 1920s or the 2080s?",
    "Would you rather be stuck in a time loop of a good day or a bad day that only lasts an hour?",
    "Would you rather have 10 years added to your life or $1,000,000?",
    "Would you rather age from the neck up or the neck down only?",
    "Would you rather find a book that explains your past or a book that predicts your future?",
    "Would you rather be an adult your whole life or a kid your whole life?",
    "Would you rather know the date of your death or the cause of your death?",
    "Would you rather live forever but everyone else ages normally, or live a normal life with your loved ones?",
    "Would you rather go back to kindergarten with everything you know now or graduate college at age 10?",
    "Would you rather lose all your old memories or never be able to make new ones?",
    "Would you rather have been born 100 years ago or 100 years from now?",
    "Would you rather have more time or more money?",
    "Would you rather know all the mysteries of the universe or know every outcome of your choices?",
    "Would you rather restart your life at age 10 or age 20?",
    "Would you rather live a short, exciting life or a long, boring life?",

    # --- Food & Drink ---
    "Would you rather never eat pizza again or never eat tacos again?",
    "Would you rather have to hunt for your own food or grow your own food?",
    "Would you rather only eat sweet foods or only eat savory foods?",
    "Would you rather give up coffee or give up soda?",
    "Would you rather eat everything with a spoon or everything with a fork?",
    "Would you rather always have a burnt tongue or always have brain freeze?",
    "Would you rather eat a raw onion or a whole lemon?",
    "Would you rather never have chocolate again or never have cheese again?",
    "Would you rather only drink water or only drink milk for the rest of your life?",
    "Would you rather eat food that is always too hot or always too cold?",
    "Would you rather give up breakfast or dinner?",
    "Would you rather cook every meal you eat or clean up after every meal you eat?",
    "Would you rather eat only white foods or only green foods?",
    "Would you rather have free Starbucks for life or free McDonald's for life?",
    "Would you rather be a vegetarian or a carnivore?",
    "Would you rather eat a meal that tastes great but smells bad, or smells great but tastes bad?",
    "Would you rather never eat dessert again or never eat snacks again?",
    "Would you rather have a personal chef or a personal housekeeper?",
    "Would you rather eat only spicy food or only bland food?",
    "Would you rather have to eat a bowl of crickets or a bowl of worms?",
    "Would you rather eat your favorite meal every day or never eat it again?",
    "Would you rather be allergic to sugar or allergic to salt?",
    "Would you rather give up fruits or vegetables?",
    "Would you rather eat only junk food and be thin or eat only healthy food and be overweight?",
    "Would you rather always get the wrong order at a restaurant or always have the service be terrible?",

    # --- Work & Productivity ---
    "Would you rather work 4 ten-hour days or 5 eight-hour days?",
    "Would you rather be the boss of a failing company or an employee at a successful company?",
    "Would you rather have a job you love that pays poorly or a job you hate that pays well?",
    "Would you rather work alone or work in a team?",
    "Would you rather have a terrible boss but a great job, or a great boss but a terrible job?",
    "Would you rather work in an office or work from home?",
    "Would you rather commute two hours to a dream job or two minutes to a boring job?",
    "Would you rather be the funniest person in the office or the smartest?",
    "Would you rather never have to work again or never have to sleep again?",
    "Would you rather have unlimited vacation time or double your salary?",
    "Would you rather be famous in your field or famous to the general public?",
    "Would you rather write a best-selling book or direct a blockbuster movie?",
    "Would you rather be a master of procrastination or a master of micromanagement?",
    "Would you rather always be 10 minutes late or always be 20 minutes early?",
    "Would you rather sit at a desk all day or stand all day?",
    "Would you rather have a physical job or a mental job?",
    "Would you rather be a teacher or a student for the rest of your life?",
    "Would you rather have a job where you talk to people all day or a job where you stay silent?",
    "Would you rather get paid daily or get paid once a year?",
    "Would you rather retire at 40 with little money or retire at 70 with a lot of money?",
    "Would you rather lose all your contacts or lose all your emails?",
    "Would you rather have a chaotic workspace or a sterile workspace?",
    "Would you rather present to a crowd of 1,000 or have dinner with a CEO?",
    "Would you rather work on weekends or work on holidays?",
    "Would you rather be criticized in public or praised in private?",

    # --- Technology & Modern Life ---
    "Would you rather give up your smartphone or your computer?",
    "Would you rather have slow internet but unlimited data or fast internet but limited data?",
    "Would you rather only be able to text or only be able to call?",
    "Would you rather give up social media or give up TV/movies?",
    "Would you rather have a battery that never dies or a screen that never cracks?",
    "Would you rather use a mouse without a scroll wheel or a keyboard without a space bar?",
    "Would you rather have to print directions for everywhere you go or use a physical map?",
    "Would you rather receive a text every time you are mentioned or never know when you are mentioned?",
    "Would you rather have your search history made public or your text messages made public?",
    "Would you rather live without electricity or without running water?",
    "Would you rather never watch YouTube again or never watch Netflix again?",
    "Would you rather lose your phone or lose your wallet?",
    "Would you rather only use voice commands for electronics or only use a stylus?",
    "Would you rather have no air conditioning or no heating?",
    "Would you rather listen to music on a record player or on a streaming service?",
    "Would you rather accidentally like an old photo of your ex or accidentally send a text to the wrong person?",
    "Would you rather have a flip phone or a pager?",
    "Would you rather delete every app on your phone or delete every photo on your phone?",
    "Would you rather never play video games again or never listen to music again?",
    "Would you rather be an influencer or a hacker?",
    "Would you rather have a self-driving car or a flying car?",
    "Would you rather live in a smart house that listens to everything or a cabin with no tech?",
    "Would you rather watch movies in black and white or without sound?",
    "Would you rather only communicate via emojis or only via voice notes?",
    "Would you rather have free Wi-Fi wherever you go or free coffee wherever you go?",

    # --- Nature & Travel ---
    "Would you rather vacation at the beach or in the mountains?",
    "Would you rather live in a treehouse or live in a cave?",
    "Would you rather never see the sun again or never see the moon again?",
    "Would you rather travel the world for a year on a shoestring budget or stay in a luxury resort for a week?",
    "Would you rather live in a place that is always hot or always cold?",
    "Would you rather go on a cruise or go camping?",
    "Would you rather visit every country in the world or go to space?",
    "Would you rather live in a big city or a small town?",
    "Would you rather be stranded on a desert island alone or with your worst enemy?",
    "Would you rather fight one horse-sized duck or 100 duck-sized horses?",
    "Would you rather live in the jungle or the desert?",
    "Would you rather see the Northern Lights or the Great Barrier Reef?",
    "Would you rather always travel by train or always travel by plane?",
    "Would you rather live on a boat or live in an RV?",
    "Would you rather encounter a bear or a shark?",
    "Would you rather hike Mount Everest or dive into the Mariana Trench?",
    "Would you rather be able to control the weather or control traffic?",
    "Would you rather live in a world without flowers or a world without trees?",
    "Would you rather never see the ocean again or never see snow again?",
    "Would you rather have a cabin in the woods or a penthouse in the city?",
    "Would you rather travel alone or travel with a large group?",
    "Would you rather sit in the middle seat or the aisle seat?",
    "Would you rather lose your luggage or lose your passport?",
    "Would you rather ride a camel or ride an elephant?",
    "Would you rather visit a volcano or a glacier?",

    # --- Body & Appearance ---
    "Would you rather have no hair or no eyebrows?",
    "Would you rather have hands that are too big or hands that are too small?",
    "Would you rather be 4 feet tall or 8 feet tall?",
    "Would you rather have a huge nose or huge ears?",
    "Would you rather have an extra toe or an extra finger?",
    "Would you rather always have a bad hair day or always have a bad outfit day?",
    "Would you rather wear a tuxedo every day or wear pajamas every day?",
    "Would you rather have blue skin or green skin?",
    "Would you rather sweat mayonnaise or cry orange juice?",
    "Would you rather have to wear a cape everywhere or wear a helmet everywhere?",
    "Would you rather have a unibrow or no eyelashes?",
    "Would you rather have feet for hands or hands for feet?",
    "Would you rather only wear neon colors or only wear gray?",
    "Would you rather have to shout everything you say or whisper everything you say?",
    "Would you rather have a permanent clown face or permanent cat whiskers?",
    "Would you rather be incredibly hairy or completely bald?",
    "Would you rather have teeth like a shark or a neck like a giraffe?",
    "Would you rather have a tail or horns?",
    "Would you rather always look tired or always look angry?",
    "Would you rather have to hop everywhere or walk backwards everywhere?",
    "Would you rather wear shoes that are too tight or shoes that are too loose?",
    "Would you rather always smell like garlic or always smell like wet dog?",
    "Would you rather have a high-pitched voice or a deep robotic voice?",
    "Would you rather have your name tattooed on your forehead or have no name at all?",
    "Would you rather never cut your nails or never cut your hair?",

    # --- Social & Personality ---
    "Would you rather be liked by everyone or respected by everyone?",
    "Would you rather be the center of attention or a wallflower?",
    "Would you rather have one best friend or many acquaintances?",
    "Would you rather be a genius in a world of idiots or an idiot in a world of geniuses?",
    "Would you rather always say exactly what you're thinking or never be able to speak again?",
    "Would you rather know everyone's secrets or have everyone know your secrets?",
    "Would you rather be feared or loved?",
    "Would you rather have a lot of friends who gossip or no friends at all?",
    "Would you rather live without music or live without books?",
    "Would you rather never be able to laugh or never be able to smile?",
    "Would you rather be famous for something embarrassing or unknown for something heroic?",
    "Would you rather always win arguments or always keep the peace?",
    "Would you rather be overly optimistic or overly pessimistic?",
    "Would you rather confront your problems head-on or ignore them until they go away?",
    "Would you rather be the funniest person in the room or the most attractive?",
    "Would you rather apologize for something you didn't do or not accept an apology you deserve?",
    "Would you rather trust everyone or trust no one?",
    "Would you rather spend a day with your celebrity crush or your role model?",
    "Would you rather be a leader or a follower?",
    "Would you rather save all your money or spend it all on experiences?",
    "Would you rather have a rewind button for conversations or a mute button for people?",
    "Would you rather be a character in a comedy or a drama?",
    "Would you rather live with your parents forever or live with your in-laws forever?",
    "Would you rather have a roommate who is messy but nice, or clean but mean?",
    "Would you rather forgive and forget or hold a grudge forever?",

    # --- Minor Inconveniences & Annoyances ---
    "Would you rather always have a stone in your shoe or always have an itch you can't reach?",
    "Would you rather have hiccups for the rest of your life or feel like you have to sneeze but can't?",
    "Would you rather have slow internet or a phone that needs charging every 2 hours?",
    "Would you rather sit in traffic for an hour or wait in line for an hour?",
    "Would you rather always have wet socks or always have cold hands?",
    "Would you rather use sandpaper as toilet paper or use hot sauce as eye drops?",
    "Would you rather have a constant ringing in your ears or a constant bad taste in your mouth?",
    "Would you rather step on a Lego every morning or stub your toe every night?",
    "Would you rather listen to a baby crying or a dog barking for 24 hours?",
    "Would you rather lose your keys or lose your phone?",
    "Would you rather have to read the terms and conditions for everything or pay double for everything?",
    "Would you rather be stuck in an elevator or stuck on a ski lift?",
    "Would you rather have a noisy neighbor or a nosy neighbor?",
    "Would you rather always be hot or always be cold?",
    "Would you rather have to use a public restroom every time or never shower again?",
    "Would you rather drop your phone in the toilet or drop your food on the floor?",
    "Would you rather have a fly buzzing around your head or a mosquito biting you?",
    "Would you rather spill coffee on your shirt or have food stuck in your teeth?",
    "Would you rather have a bad haircut or a bad dye job?",
    "Would you rather forget people's names or forget people's faces?",
    "Would you rather always have chapped lips or always have dandruff?",
    "Would you rather have to hand-wash all your dishes or hand-wash all your clothes?",
    "Would you rather have a squeaky voice or a squeaky walk?",
    "Would you rather have no pillows or no blankets?",
    "Would you rather always hit red lights or always get stuck behind a slow walker?",

    # --- Random & Hypothetical ---
    "Would you rather know the truth about aliens or the truth about ghosts?",
    "Would you rather live in the Harry Potter universe or the Star Wars universe?",
    "Would you rather be a dragon or own a dragon?",
    "Would you rather have a magic carpet or a flying broomstick?",
    "Would you rather survive a zombie apocalypse or a robot uprising?",
    "Would you rather be a superhero or a supervillain?",
    "Would you rather live in a world made of Lego or a world made of clay?",
    "Would you rather meet a real alien or a real dinosaur?",
    "Would you rather be a master thief or a master detective?",
    "Would you rather have the ability to talk to plants or talk to machines?",
    "Would you rather live in a haunted house or a house with no windows?",
    "Would you rather be a character in a video game or a character in a book?",
    "Would you rather win the lottery or win the Nobel Peace Prize?",
    "Would you rather be an Olympic athlete or a famous musician?",
    "Would you rather have the life of a cat or the life of a dog?",
    "Would you rather be a mermaid/merman or a centaur?",
    "Would you rather have a bottomless bank account or a bottomless plate of food?",
    "Would you rather find a treasure chest or find a genie lamp?",
    "Would you rather be able to jump as high as a building or dig as fast as a mole?",
    "Would you rather have finger-guns that actually work or eyes that shoot lasers?",
    "Would you rather be made of glass or be made of rubber?",
    "Would you rather live in a submarine or a space station?",
    "Would you rather face a T-Rex or a pack of Velociraptors?",
    "Would you rather be the first person on Mars or the last person on Earth?",
    "Would you rather have a pause button for your life or a volume knob for your life?"
]

NSFW_WOULD_YOU_RATHER = [
    "Would you rather have sex with someone you love but terrible chemistry or amazing sex with someone you don't love?",
    "Would you rather your partner be amazing in bed but terrible at communicating or great at communicating but bad in bed?",
    "Would you rather have your browsing history made public or your text messages made public?",
    "Would you rather have sex only in the missionary position for the rest of your life or never have sex in the missionary position again?",
    "Would you rather walk in on your parents having sex or have your parents walk in on you having sex?",
    "Would you rather have sex only once a week or masturbate only once a week?",
    "Would you rather date someone who's amazing in bed but boring personality or terrible in bed but amazing personality?",
    "Would you rather have your worst enemy see your nudes or your boss see your nudes?",
    "Would you rather have an amazing one-night stand or mediocre sex with someone you love?",
    "Would you rather be caught masturbating by your crush or by your parents?",
    "Would you rather be the dominant partner always or the submissive partner always?",
    "Would you rather have sex with the lights on always or with the lights off always?",
    "Would you rather have your partner fake an orgasm every time or never orgasm but always be honest about it?",
    "Would you rather be known for being amazing at oral sex or amazing at regular sex?",
    "Would you rather have a partner who's extremely kinky or extremely vanilla?",
    "Would you rather accidentally send a nude to your boss or to your ex?",
    "Would you rather have sex in a public place and risk getting caught or never have sex anywhere but your bedroom?",
    "Would you rather have your partner be a screamer or completely silent during sex?",
    "Would you rather find out your partner has been faking their orgasms or that they've been thinking about someone else during sex?",
    "Would you rather have amazing foreplay but disappointing sex or skip foreplay but have amazing sex?",
    "Would you rather have your sex tape leaked online or your diary published in a newspaper?",
    "Would you rather be with someone who wants sex way more than you or way less than you?",
    "Would you rather have a partner who's selfish in bed but generous everywhere else or generous in bed but selfish everywhere else?",
    "Would you rather accidentally call out your ex's name during sex or have your partner call out their ex's name?",
    "Would you rather have sex only when you're both drunk or only when you're both completely sober?",
    "Would you rather have the best sex of your life but never see that person again or have mediocre sex with your soulmate?",
    "Would you rather be with someone who has absolutely no experience or someone who has been with 100+ people?",
    "Would you rather have your parents see your search history or your children (when they're adults) see your search history?",
    "Would you rather be amazing at giving pleasure but never receive it or amazing at receiving but terrible at giving?",
    "Would you rather have your partner be extremely jealous but faithful or completely trusting but unfaithful?",
    "Would you rather have to describe your favorite sexual position to your parents or demonstrate it (clothed) to your friends?",
    "Would you rather have sex only on special occasions (birthdays, holidays) or have sex every day but it's always boring?",
    "Would you rather have your partner always want to try new things in bed (even weird ones) or never want to try anything new?",
    "Would you rather be with someone who finishes too quickly or someone who takes forever to finish?",
    "Would you rather have amazing sex but your partner never wants to cuddle after or terrible sex but amazing aftercare?",
    "Would you rather be in a relationship with no sex or have sex with no emotional connection?",
    "Would you rather have your most embarrassing sexual fantasy come true or have your partner's most embarrassing fantasy come true?",
    "Would you rather be with someone who's amazing at dirty talk or someone who's amazing with their hands?",
    "Would you rather have sex only in complete darkness or only in broad daylight?",
    "Would you rather have to always make the first move or never be allowed to make the first move?",
    "Would you rather be with someone who's extremely attractive but bad in bed or average looking but incredible in bed?",
    "Would you rather have your partner be too rough or too gentle?",
    "Would you rather have sex interrupted by your parents calling or by the police knocking?",
    "Would you rather be in a sexless relationship with your perfect emotional match or a purely physical relationship with no emotional connection?",
    "Would you rather have your partner always want to be on top or always want to be on bottom?",
    "Would you rather have amazing sexual chemistry but fight constantly outside the bedroom or get along perfectly but have no chemistry?",
    "Would you rather be with someone who's extremely vocal about what they want or someone who never tells you what they like?",
    "Would you rather have sex only when you're in love or only when you're not in love?",
    "Would you rather have your worst hookup story go viral or have your best hookup story never be believed?",
    "Would you rather be with someone who's a perfectionist in bed or someone who doesn't care about performance?",
    "Would you rather have to always shower before sex or never be allowed to shower before sex?",
    "Would you rather be incredible at one specific sexual act or mediocre at everything?",
    "Would you rather have your partner always want to do it in the morning or always at night?",
    "Would you rather be with someone who's extremely kinky but only in private or someone who's vanilla but adventurous in public?",
    "Would you rather have to use toys every time or never be allowed to use toys?",
    "Would you rather be with someone who wants to film your intimate moments or someone who won't even let you see them naked?",
    "Would you rather have a partner who's amazing at sexting but terrible in person or terrible at sexting but amazing in person?",
    "Would you rather have to tell your partner every sexual thought you have or never be allowed to share your fantasies?",
    "Would you rather be with someone who's extremely experienced but compares you to past partners or someone inexperienced who makes mistakes?",
    "Would you rather have incredible chemistry with someone you can't stand as a person or be best friends with someone you have zero attraction to?",
    "Would you rather have your partner always want quickies or always want hours-long sessions?",
    "Would you rather be with someone who's selfish during sex but thoughtful everywhere else or thoughtful during sex but selfish everywhere else?",
    "Would you rather have to always initiate everything or never be allowed to initiate anything?",
    "Would you rather be with someone who's completely silent during sex or someone who won't stop talking during sex?",
    "Would you rather have amazing phone sex but terrible in-person sex or terrible phone sex but amazing in-person sex?",
    "Would you rather be with someone who always wants to try new positions or someone who only wants to do the same position?",
    "Would you rather have your partner be extremely submissive in bed but dominant everywhere else or dominant in bed but submissive everywhere else?",
    "Would you rather have to always have music playing during sex or always have complete silence?",
    "Would you rather be with someone who takes forever to get in the mood or someone who's always ready but finishes too quickly?",
    "Would you rather have amazing sexual tension but never act on it or act on it but have no tension afterward?",
    "Would you rather be with someone who's amazing at teasing but never follows through or someone who skips all foreplay but delivers?",
    "Would you rather have your ideal physical type but terrible personality in bed or your ideal personality but not your physical type?",
    "Would you rather be with someone who always wants to be in control or someone who never wants any responsibility?",
    "Would you rather have sex with someone who's amazing at foreplay but terrible at the main event or someone who skips foreplay but is incredible at sex?",
    "Would you rather be with someone who wants to try everything once or someone who only wants to do what they know they like?",
    "Would you rather have your partner be extremely adventurous in bed but vanilla in life or vanilla in bed but adventurous in life?",
    "Would you rather be with someone who's always ready to go or someone who needs a lot of buildup?",
    "Would you rather have sex with someone who's extremely vocal or someone who's completely silent?",
    "Would you rather be with someone who wants to experiment with kinks or someone who's satisfied with basics?",
    "Would you rather have your partner be extremely dominant in bed but submissive in life or submissive in bed but dominant in life?",
    "Would you rather be with someone who's extremely experienced but compares you to others or someone inexperienced who makes mistakes?",
    "Would you rather have sex with someone who's extremely attractive but bad in bed or someone average looking but incredible in bed?",
    "Would you rather be with someone who wants to film everything or someone who won't even let you see them naked?",
    "Would you rather have your partner be extremely kinky but only in private or vanilla but adventurous in public?",
    "Would you rather be with someone who's amazing at sexting but terrible in person or terrible at sexting but amazing in person?",
    "Would you rather have sex with someone who always wants to be on top or always wants to be on bottom?",
    "Would you rather be with someone who's extremely rough or extremely gentle?",
    "Would you rather have your partner be extremely jealous but faithful or completely trusting but unfaithful?",
    "Would you rather be with someone who wants to try new positions constantly or someone who only wants one position?",
    "Would you rather have sex with someone who's extremely selfish in bed but generous in life or generous in bed but selfish in life?",
    "Would you rather be with someone who's extremely vocal about what they want or someone who never tells you what they like?",
    "Would you rather have your partner be extremely submissive in bed but dominant in life or dominant in bed but submissive in life?",
    "Would you rather be with someone who always wants to do it in the morning or always at night?",
    "Would you rather have sex with someone who wants to use toys every time or never wants to use toys?",
    "Would you rather be with someone who's extremely kinky but only wants to do it once a week or vanilla but wants it daily?",
    "Would you rather have your partner be extremely experienced but tells you about past partners or inexperienced but makes mistakes?",
    "Would you rather be with someone who's extremely attractive but has no personality or average looking but amazing personality?",
    "Would you rather have sex with someone who wants to film your intimate moments or someone who won't even let you see them naked?",
    "Would you rather be with someone who's extremely kinky but only in private or vanilla but adventurous in public?",
    "Would you rather have your partner be amazing at sexting but terrible in person or terrible at sexting but amazing in person?",
    "Would you rather be with someone who always wants to be on top or always wants to be on bottom?",
    "Would you rather have sex with someone who's extremely rough or extremely gentle?",
    "Would you rather be with someone who's extremely jealous but faithful or completely trusting but unfaithful?",
    "Would you rather have your partner want to try new positions constantly or only want one position?",
    "Would you rather be with someone who's extremely selfish in bed but generous in life or generous in bed but selfish in life?",
    "Would you rather have sex with someone who's extremely vocal about what they want or someone who never tells you what they like?",
    "Would you rather be with someone who's extremely submissive in bed but dominant in life or dominant in bed but submissive in life?",
    "Would you rather have your partner always want to do it in the morning or always at night?",
    "Would you rather be with someone who wants to use toys every time or never wants to use toys?",
    "Would you rather have sex with someone who's extremely kinky but only wants to do it once a week or vanilla but wants it daily?",
    "Would you rather be with someone who's extremely experienced but tells you about past partners or inexperienced but makes mistakes?",
    "Would you rather have your partner be extremely attractive but has no personality or average looking but amazing personality?",
    "Would you rather be with someone who wants to film your intimate moments or someone who won't even let you see them naked?",
    "Would you rather have sex with someone who's extremely kinky but only in private or vanilla but adventurous in public?",
    "Would you rather be with someone who's amazing at sexting but terrible in person or terrible at sexting but amazing in person?",
    "Would you rather have your partner always want to be on top or always want to be on bottom?",
    "Would you rather be with someone who's extremely rough or extremely gentle?",
    "Would you rather have sex with someone who's extremely jealous but faithful or completely trusting but unfaithful?",
    "Would you rather be with someone who wants to try new positions constantly or only wants one position?",
    "Would you rather have your partner be extremely selfish in bed but generous in life or generous in bed but selfish in life?",
    "Would you rather be with someone who's extremely vocal about what they want or someone who never tells you what they like?",
    "Would you rather have sex with someone who's a 10/10 in looks but 2/10 in bed or 2/10 in looks but 10/10 in bed?",
    "Would you rather have your partner want to roleplay every time or never want to roleplay?",
    "Would you rather be with someone who's extremely vanilla but wants it 3 times a day or extremely kinky but only wants it once a week?",
    "Would you rather have sex with someone who's extremely clean and hygienic but boring or adventurous but not as clean?",
    "Would you rather be with someone who's extremely confident in bed but insecure in life or insecure in bed but confident in life?",
    "Would you rather have your partner be extremely experimental but makes mistakes or extremely careful but never tries anything new?",
    "Would you rather be with someone who's extremely passionate but rough or extremely gentle but boring?",
    "Would you rather have sex with someone who's extremely focused on your pleasure or extremely focused on their own pleasure?",
    "Would you rather be with someone who's extremely romantic in bed but not in life or romantic in life but not in bed?",
    "Would you rather have your partner be extremely vocal during sex or extremely quiet during sex?",
    "Would you rather be with someone who's extremely experienced but judgmental or inexperienced but accepting?",
    "Would you rather have sex with someone who's extremely attractive but lazy or average looking but extremely enthusiastic?",
    "Would you rather be with someone who wants to try BDSM or someone who's completely against it?",
    "Would you rather have your partner be extremely dominant but only in bed or extremely submissive but only in bed?",
    "Would you rather be with someone who's extremely kinky but only wants quickies or vanilla but wants long sessions?",
    "Would you rather have sex with someone who's extremely experimental but unsafe or extremely safe but boring?",
    "Would you rather be with someone who's extremely passionate but unpredictable or extremely predictable but reliable?",
    "Would you rather have your partner be extremely focused on foreplay or extremely focused on the main event?",
    "Would you rather be with someone who's extremely experienced but compares you or inexperienced but learns with you?",
    "Would you rather have sex with someone who's extremely attractive but selfish or average looking but selfless?",
    "Would you rather be with someone who wants to try everything or someone who only wants basics?",
    "Would you rather have your partner be extremely kinky but only in private or vanilla but adventurous in public?",
    "Would you rather be with someone who's extremely experimental but makes mistakes or extremely careful but never experiments?",
    "Would you rather have sex with someone who's extremely passionate but rough or extremely gentle but less passionate?",
    "Would you rather be with someone who's extremely focused on your pleasure or extremely focused on their own?",
    "Would you rather have your partner be extremely romantic in bed but not in life or romantic in life but not in bed?",
    "Would you rather be with someone who's extremely vocal during sex or extremely quiet?",
    "Would you rather have sex with someone who's extremely experienced but judgmental or inexperienced but accepting?",
    "Would you rather be with someone who's extremely attractive but lazy or average looking but enthusiastic?",
    "Would you rather have your partner want to try BDSM or be completely against it?",
    "Would you rather be with someone who's extremely dominant but only in bed or extremely submissive but only in bed?",
    "Would you rather have sex with someone who's extremely kinky but only wants quickies or vanilla but wants long sessions?",
    "Would you rather be with someone who's extremely experimental but unsafe or extremely safe but boring?",
    "Would you rather have your partner be extremely passionate but unpredictable or extremely predictable but reliable?",
    "Would you rather be with someone who's extremely focused on foreplay or extremely focused on the main event?",
    "Would you rather have sex with someone who's extremely experienced but compares you or inexperienced but learns with you?",
    "Would you rather be with someone who's extremely attractive but selfish or average looking but selfless?",
    "Would you rather have your partner want to try everything or only want basics?",
    "Would you rather be with someone who's extremely kinky but only in private or vanilla but adventurous in public?",
    "Would you rather have sex with someone who's extremely experimental but makes mistakes or extremely careful but never experiments?",
    "Would you rather be with someone who's extremely passionate but rough or extremely gentle but less passionate?",
    "Would you rather have your partner be extremely focused on your pleasure or extremely focused on their own?",
    "Would you rather be with someone who's extremely romantic in bed but not in life or romantic in life but not in bed?",
    "Would you rather have sex with someone who's extremely vocal during sex or extremely quiet?",
    "Would you rather be with someone who's extremely experienced but judgmental or inexperienced but accepting?",
    "Would you rather have your partner be extremely attractive but lazy or average looking but enthusiastic?",
    "Would you rather be with someone who wants to try BDSM or be completely against it?",
    "Would you rather have sex with someone who's extremely dominant but only in bed or extremely submissive but only in bed?",
    "Would you rather be with someone who's extremely kinky but only wants quickies or vanilla but wants long sessions?"
]

# Forfeits for not completing a dare
FORFEITS = [
    "Tell the group an embarrassing (but SFW) story about yourself.",
    "Let the group choose a funny (SFW) nickname for you for the next hour.",
    "Post \"I forfeited a dare!\" in the chat.",
    "Do 5 push-ups (or another simple exercise) right now.",
    "Compliment the person who dared you.",
    "Speak in a silly voice until your next turn.",
    "Change your profile picture to something silly (chosen by the group?) for 10 minutes.",
    "Tell a dad joke.",
    "Try to lick your nose.",
    "Let someone else ask you a SFW Truth question."
]