# League related constants
LEAGUE_REGIONS = [
    "EUW1", "EUN1", "TR1", "RU", "NA1", "BR1", "LA1", "LA2",
    "JP1", "KR", "OC1", "SG2", "TW2", "VN2"
]

LEAGUE_QUEUE_TYPE_NAMES = {
    "RANKED_SOLO_5x5": "Ranked Solo/Duo",
    "RANKED_FLEX_SR": "Ranked Flex 5v5",
    "CHERRY": "Arena",
    "KIWI": "ARAM Mayhem"
}

TFT_QUEUE_TYPE_NAMES = {
    "RANKED_TFT": "Ranked TFT",
}

# Region to routing cluster mapping for match history endpoints
REGION_TO_ROUTING = {
    "NA1": "americas", "BR1": "americas", "LA1": "americas", "LA2": "americas",
    "EUW1": "europe", "EUN1": "europe", "TR1": "europe", "RU": "europe",
    "JP1": "asia", "KR": "asia",
    "OC1": "sea", "SG2": "sea", "TW2": "sea", "VN2": "sea"
}

# Platform mappings for Apex Legends
APEX_PLATFORM_MAPPING = {
    'Xbox': 'xbl',
    'Playstation': 'psn',
    'Origin (PC)': 'origin',
}

# Time mapping for Fortnite
FORTNITE_TIME_MAPPING = {
    'Season': 'season',
    'Lifetime': 'lifetime',
}

# Special emoji name mappings for League of Legends
SPECIAL_EMOJI_NAMES = {
    "Renata Glasc": "Renata",
    "Wukong": "MonkeyKing",
    "Miss Fortune": "MissFortune",
    "Xin Zhao": "XinZhao",
    "Aurelion Sol": "AurelionSol",
    "Bel'Veth": "Belveth",
    "Cho'Gath": "Chogath",
    "Nunu & Willump": "Nunu",
    "Lee Sin": "LeeSin",
    "K'Sante": "KSante",
    "Kog'Maw": "KogMaw",
    "Twisted Fate": "TwistedFate",
    "Dr. Mundo": "DrMundo",
    "Rek'Sai": "RekSai",
    "Kai'Sa": "KaiSa",
    "Vel'Koz": "Velkoz",
    "Kha'Zix": "Khazix",
    "Master Yi": "MasterYi",
}

# Latest bot updates

LATEST_UPDATES = (
    "## 🎉 Version 2.10.1\n\n"
    "### 🔧 Improvements\n\n"
    "**Fortnite Command**\n"
    "• Name parameter is now required for better user experience\n\n"
    "**Support Links**\n"
    "• All support-related commands and links now direct to astrostats.info/support\n"
    "• Updated `/bug` and `/feedback` commands to link to support page\n"
    "• Consistent support navigation across all commands\n\n"
    "Visit [astrostats.info](https://astrostats.info) for more information."
)

SFW_TRUTHS = [
    "If you could have any superpower, what would it be and why?",
    "What's the most embarrassing thing that happened to you in school?",
    "What's a skill you wish you had?",
    "What's your guilty pleasure song or artist?",
    "If you could travel anywhere in the world right now, where would you go?",
    "What movie can you watch over and over again without getting tired of it?",
    "What's the weirdest food combination you genuinely enjoy?",
    "Who was your first celebrity crush?",
    "What's one thing you're really proud of accomplishing?",
    "If you were an animal, what would you be and why?",
    "What's the last book you read? Did you enjoy it?",
    "What is your biggest pet peeve?",
    "What's your favorite season and why?",
    "If you could meet any historical figure, who would it be?",
    "What's the strangest dream you've ever had?",
    "What hobby would you get into if time and money weren't an issue?",
    "What's your favorite type of weather?",
    "If you had to eat one meal for the rest of your life, what would it be?",
    "What was your favorite cartoon show as a kid?",
    "What's something you believed for way too long as a child?",
    "What's the best piece of advice you've ever received?",
    "Are you a morning person or a night owl?",
    "What's your go-to comfort food?",
    "If you could instantly learn any language, which one would you choose?",
    "What's the funniest joke you know by heart?",
    "What's something popular now that you just don't understand?",
    "Have you ever been told you look like a celebrity? Who?",
    "What's your favorite board game or card game?",
    "If you could eliminate one chore forever, what would it be?",
    "What's the most useless talent you have?",
    "What's your favorite holiday?",
    "What's a common misconception people have about you?",
    "If your pet could talk, what's the first question you'd ask it?",
    "What's the most memorable concert or live event you've attended?",
    "What's something you're currently learning or want to learn?",
    "What's your favorite way to relax?",
    "If you were stranded on a desert island, what three *non-essential* items would you want?",
    "What's the kindest thing someone has ever done for you?",
    "What fashion trend do you regret participating in?",
    "What fictional world would you love to live in?",
    "What's your biggest fear (that's relatively irrational)?",
    "What instrument do you wish you could play?",
    "What's the most interesting documentary you've watched?",
    "If you could switch lives with someone for a day, who would it be?",
    "What's your favorite pizza topping?",
    "What's something you're really bad at?",
    "What's the most beautiful place you've ever visited?",
    "What's your spirit animal?",
    "If you found a lottery ticket that won £10,000, what's the first thing you'd buy?",
    "What's a word you always misspell?",
    "What's your favorite type of dessert?",
    "Have you ever met someone famous?",
    "What's the best gift you've ever given or received?",
    "If you could invent anything, what problem would it solve?",
    "What topic could you give a 30-minute presentation on with no preparation?",
    "What's your favorite childhood memory?",
    "What's the silliest argument you've ever been in?",
    "If you had a warning label, what would it say?",
    "What song instantly puts you in a good mood?",
    "What's something you wish you were better at?",
    "What's the weirdest thing you've ever eaten?",
    "What's your dream job (even if it's unrealistic)?",
    "What do you procrastinate on the most?",
    "What's your favourite thing about where you live?",
    "If you could talk to your past self (age 15), what one piece of advice would you give?",
    "What's one small thing that makes your day better?",
    "What's the longest you've gone without sleep?",
    "If you could bring back one extinct animal, which would it be?",
    "What's a movie that made you cry?",
    "What's your favourite type of art (music, painting, literature, etc.)?",
    "What's something you learned recently that surprised you?",
    "What weird smell do you secretly like?",
    "What's the most adventurous thing you've ever done?",
    "If you were a ghost, who or where would you haunt?",
    "What's one rule you wish you could break without consequence?"
]
SFW_DARES = [
    "Do your best impression of a famous celebrity chosen by the group (use voice if possible, otherwise describe it).",
    "Talk in a funny accent (e.g., pirate, robot, posh) in voice chat until your next turn (or type 3 messages in that accent).",
    "Try to juggle 3 safe items you have nearby (like socks or small fruit) for 15 seconds. Report your success.",
    "Do 10 real push-ups or 20 jumping jacks right now. Confirm when done.",
    "Sing the chorus of your favorite song out loud (use voice if possible).",
    "Wear socks on your hands for the next 10 minutes.",
    "Try to lick your elbow. Report if you succeeded.",
    "Speak only in rhymes for the next 3 messages you send.",
    "Make up a short rap about someone else in the chat and say it/type it.",
    "Balance a spoon on your nose for 10 seconds. Report success.",
    "Act like a cat until your next turn (meow in voice, or use cat-like typing).",
    "Tell a cheesy joke. If no one laughs (reacts), tell another one.",
    "Make the ugliest face you possibly can (show on camera if possible, otherwise describe it).",
    "Let the group choose a funny (SFW) word. Work it into your next 3 spoken/typed sentences naturally.",
    "Do your best chicken dance for 15 seconds. Confirm when done.",
    "Pretend to be a statue for 1 minute – no moving, typing, or reacting! Confirm when done.",
    "Try to pat your head and rub your stomach at the same time for 10 seconds. Report success.",
    "Blindfolded, have someone nearby hand you an object. Guess it by touch in 3 tries.",
    "Give a dramatic reading of a random paragraph from a physical book or webpage you have open.",
    "Build a small tower (at least 3 items high) out of objects on your desk in 60 seconds. Send a picture or describe it.",
    "Try to say the alphabet backward out loud as fast as you can.",
    "Draw a picture of another user's avatar using pen and paper with your non-dominant hand. Send a picture.",
    "Do an impression of another player (voice or text) until someone guesses who it is.",
    "Invent a new, silly handshake and teach it to someone nearby (or describe it).",
    "Wear an item of clothing backward until your next turn.",
    "Pretend you are a news reporter reporting live from your room.",
    "Try to touch your nose with your tongue. Report success.",
    "Make up a short story, but each word must start with the same letter (say or type it).",
    "Hop on one foot for 30 seconds. Confirm when done.",
    "Let someone else style your hair messily (if possible). Send a picture or describe.",
    "Act out a scene from your favorite movie (use voice/camera if possible).",
    "Try to whistle a song chosen by the group.",
    "Do your best runway model walk across your room. Confirm when done.",
    "Pretend to be a flight attendant giving safety instructions for your chair.",
    "Speak like Yoda for your next 3 messages/sentences.",
    "Try to fold a piece of paper more than 7 times.",
    "Tell the group your most embarrassing autocorrect fail.",
    "Make 3 different animal noises chosen by the group (use voice if possible).",
    "Act like a T-Rex (short arms, stomp feet) for 30 seconds. Confirm when done.",
    "Give a genuine compliment to everyone currently active in chat/voice.",
    "Spin around 5 times and then try to walk in a straight line. Report success.",
    "Wear a funny hat (or make one out of paper) for the next 10 minutes. Send a picture.",
    "Let someone draw a (washable) mustache on your face. Send a picture.",
    "Moonwalk across your room. Confirm when done.",
    "Recite a nursery rhyme in a scary voice (use voice if possible).",
    "Try to make someone else in the group laugh without touching them or talking (use camera/gestures if possible).",
    "Eat a spoonful of a weird (but safe!) food combination you can make right now (e.g., peanut butter and pickles). Describe the taste.",
    "Put an ice cube down your shirt/back and keep it there for 30 seconds.",
    "Try to write your name in the air using your foot.",
    "Act out your favorite emoji physically.",
    "Go outside (or to a window) and yell 'I love [Something silly]!' at the top of your lungs.",
    "Make a funny face and hold it for 1 minute (show on cam if possible).",
    "Text a friend 'Did you see that purple squirrel?' and show the response (blur name).",
    "Pretend to be an old person complaining about something near you.",
    "Try to name 5 countries starting with the letter 'P' in 15 seconds out loud.",
    "Wear your trousers/shorts/skirt on your head like a hat for 5 minutes. Send pic.",
    "Do 10 air squats right now.",
    "Try to mimic the voice of another player (if in voice).",
    "Let someone tickle you for 20 seconds (if someone is nearby!).",
    "Describe what you had for breakfast, but make it sound incredibly dramatic.",
    "Act like you are secretly a spy communicating via gestures or coded words.",
    "Try to lick your own nose. Report success.",
    "Build a mini fort using pillows/blankets near you.",
    "Make up a theme song for yourself and sing/say it.",
    "Tell a short story using only physical gestures (show on cam if possible).",
    "Try to keep a straight face while everyone else tries to make you laugh for 1 minute (show on cam if possible).",
    "Do an impression of a cartoon character (voice if possible).",
    "Walk backward around your room once.",
    "Pretend your arms are noodles for the next minute.",
    "Try to say 'Red lorry, yellow lorry' five times fast out loud.",
    "Invent a secret handshake with someone nearby (or describe one).",
    "Act like a dog playing fetch for 30 seconds.",
    "Try to solve a simple math problem (like 17x6) out loud without a calculator.",
    "Give yourself a funny nickname and introduce yourself with it until your next turn.",
    "Use finger puppets (just your fingers) to act out a short scene (show on cam if possible)."
]
NSFW_TRUTHS = [
    "What's the biggest secret you've kept from a partner?",
    "What's your 'type' physically?",
    "Have you ever skinny-dipped? Where and with whom?",
    "What's the most embarrassing thing you've searched for online?",
    "Describe your most awkward date.",
    "What's one thing you find attractive that most people might not?",
    "Have you ever used a dating app? Which one and what was your best/worst experience?",
    "What's a fantasy you've never told anyone?",
    "What's the naughtiest thing you've done in public?",
    "How important is physical intimacy to you in a relationship (scale of 1-10)?",
    "Have you ever been caught doing something intimate?",
    "What's the longest you've gone without sex?",
    "What's your biggest turn-on?",
    "What's your biggest turn-off?",
    "Have you ever faked an orgasm?",
    "What's the weirdest place you've ever hooked up with someone?",
    "Do you have any fetishes? What are they?",
    "What's something you're self-conscious about regarding your body?",
    "Have you ever had a one-night stand? Regret it?",
    "What's the most scandalous photo or video on your phone right now?",
    "Have you ever sent nudes? To whom?",
    "What's your 'number' (number of partners)?",
    "What do you think about friends with benefits?",
    "Have you ever cheated on a partner (emotionally or physically)?",
    "Have you ever been cheated on?",
    "What's the most adventurous thing you've done in the bedroom?",
    "Do you prefer giving or receiving?",
    "What's something you find surprisingly sexy?",
    "Have you ever watched porn with a partner?",
    "What's your opinion on public displays of affection?",
    "What's the kinkiest thing you're willing to admit to trying?",
    "Have you ever lied about your sexual history?",
    "What's your favorite part of your own body?",
    "What's your favorite part of a potential partner's body?",
    "Have you ever had a crush on a friend's partner?",
    "What's the worst thing someone has said to you during/after sex?",
    "What's the best compliment someone has given you during/after sex?",
    "Do you prefer morning sex or night sex?",
    "What's your go-to move to initiate intimacy?",
    "Have you ever used sex toys? Which ones?",
    "What's the most embarrassing noise you've made during sex?",
    "Have you ever stalked an ex or crush on social media?",
    "What's the minimum amount of time you need to know someone before sleeping with them?",
    "What's your opinion on sexting?",
    "Have you ever fantasized about someone in this room/group?",
    "What's the biggest romantic risk you've ever taken?",
    "What's your favourite position?",
    "Have you ever done 'the walk of shame'?",
    "What's the most disappointing sexual experience you've had?",
    "What song gets you in the mood?",
    "Have you ever been caught masturbating?",
    "What's your biggest insecurity in a relationship?",
    "What physical feature do you find most attractive?",
    "Have you ever paid for sex or been paid for sex?",
    "What's the most intimate thing you've done with someone non-sexually?",
    "What's your 'hall pass' celebrity?",
    "Would you rather have amazing sex or an amazing meal?",
    "Have you ever lied to get out of sex?",
    "What's the strangest thing that turns you on?",
    "Have you ever role-played in the bedroom?",
    "What's your favorite lingerie or type of underwear (on yourself or partner)?",
    "Have you ever had sex outdoors?",
    "What's the most public place you've fooled around?",
    "What's something you wish your partner (current or past) did more/less of?",
    "Have you ever regretted sleeping with someone?",
    "What's the biggest age gap you'd be comfortable with in a partner?",
    "Have you ever considered an open relationship?",
    "What's the first thing you notice attractive about someone?",
    "Have you ever had a threesome or considered one?",
    "What's the most inappropriate time you've felt aroused?",
    "Do you believe in love at first sight?",
    "What's your definition of 'cheating'?",
    "Have you ever had a sex dream about someone unexpected?",
    "What's the most overrated sexual act, in your opinion?",
    "What's one question you hope you don't get asked?"
]
NSFW_DARES = [
    "Send a flirty text to the last person you messaged (blur name!) and show the group.",
    "Describe your ideal romantic/intimate evening in sensual detail (voice or text).",
    "Remove one item of clothing (your choice, within comfort). Confirm when done.",
    "Let someone in the group suggest where to draw a (non-permanent) suggestive shape on your arm/leg. Send pic.",
    "Give a seductive explanation (voice or text) of how to make toast or tie shoelaces.",
    "Whisper a secret desire or fantasy into the mic (or DM someone if not in voice).",
    "Do a 'sexy' dance for 30 seconds (camera on if comfortable, otherwise confirm completion).",
    "Lick whipped cream, honey, or chocolate sauce off your own finger/hand seductively (camera on if comfortable).",
    "Read the last R-rated text message you sent or received out loud (omit names).",
    "Swap one item of clothing with someone nearby for the next round (if possible).",
    "Take a 'body shot' off yourself (lick salt, take shot/drink, suck lime) - e.g., from your arm.",
    "Give a sensual massage (shoulder, neck, hand) to yourself or someone nearby for 1 minute.",
    "Post an old, embarrassing (but SFW) picture of yourself to the chat.",
    "Show the group the most suggestive *SFW* photo on your phone (can be art, meme, etc.).",
    "Write a short, steamy sentence about the person to your left (or previous chatter) on paper and show it.",
    "Re-enact your first kiss (with a pillow or your hand).",
    "Let someone lightly spank you (if someone is nearby and consents!).",
    "Remove your socks using only your teeth.",
    "Try to seduce an inanimate object near you (like a lamp or chair) for 1 minute (voice/camera if possible).",
    "Send a voice note to someone (outside the game, with permission) saying 'I miss you' in your most seductive voice.",
    "Let the group pick a dare for you from a list of 3 *real-life* options you provide.",
    "Take off your shirt/top for the next round (wear bra/undershirt if applicable). Confirm when done.",
    "Describe your perfect partner using only suggestive adjectives (voice or text).",
    "Truth or Dare? If you pick Dare again, you have to do *two* dares next time.",
    "Give someone nearby (or a pillow) a lap dance (can be silly or serious) for 30 seconds.",
    "Show the group your phone's *photo gallery thumbnail view* for 5 seconds (careful!).",
    "Let someone suggest a word to write on your stomach/back with a washable marker (show pic if comfortable).",
    "Eat a piece of fruit (like a banana or strawberry) in the most provocative way possible (camera on if comfortable).",
    "Make 'bedroom eyes' at the camera or describe them for a full minute.",
    "Call a friend and pretend you're breaking up with them (then reveal it's a dare!).",
    "Apply lipstick/chapstick without using a mirror. Send a picture.",
    "Let someone blindfold you and feed you a common food item (if possible). Guess what it is.",
    "Do your best 'orgasm face' (camera on if comfortable).",
    "Go into another room, take a slightly suggestive selfie (SFW, face/shoulders up), and send it to the group.",
    "Tell a dirty joke (voice or text).",
    "Remove your trousers/skirt/shorts for the rest of the game (wear underwear!). Confirm when done.",
    "Act out your favorite sex position using only your hands (camera on if comfortable).",
    "Let someone pour a cup of cold water on your feet.",
    "Serenade someone in the group with a love song (voice or text).",
    "Stick out your tongue and let someone nearby place a piece of candy or fruit on it (if possible).",
    "Let the group look through your music playlist history for 1 minute (share screen?).",
    "Slowly lick a lollipop or ice cream cone (camera on if comfortable).",
    "Text your crush or partner 'What are you wearing?' right now. Share response if comfortable.",
    "Put on blindfold, spin around, and kiss the first object/wall you touch.",
    "Let someone else choose who you have to blow a kiss to (camera on if possible).",
    "Give yourself or someone nearby a hickey (requires consent!).",
    "Pretend to orgasm loudly (use voice if possible).",
    "Let someone nearby sniff your neck or hair (if possible and consent given).",
    "Take a shot of a safe drink (juice, water, soda - or alcohol if applicable/legal/safe).",
    "Wear an item of clothing as underwear (e.g., sock in bra/pants) for the next round.",
    "Slow dance by yourself or with someone nearby for one song.",
    "Let someone put lipstick on you while you're blindfolded (if possible). Send pic.",
    "Make loud slurping noises while drinking something.",
    "Confess your kinkiest thought right now (voice or text).",
    "Let someone tie your hands loosely behind your back with a scarf for 5 minutes (if possible).",
    "Take a bite out of a raw onion or lemon wedge. Describe reaction.",
    "Show the group your 'O' face (camera on if comfortable).",
    "Write a sexy poem about an object in your room and read/show it.",
    "Let someone DM you something naughty (SFW text only) and read it aloud dramatically.",
    "Do a strip tease removing only one agreed-upon item (e.g., hat, sock, glove).",
    "Make out with your own hand for 15 seconds.",
    "Try to remove your own bra/shirt with only one hand.",
    "Let the group post a harmlessly embarrassing status update on one of your social media accounts (you type it).",
    "Massage your own feet for 1 minute.",
    "Stick your finger in your own ear gently.",
    "Blindfold yourself and guess who is talking based on their voice (if in voice chat).",
    "Let someone nearby pour a little bit of their drink into your mouth (if possible/safe).",
    "Describe your ideal foreplay scenario (voice or text).",
    "Let someone take a picture of your feet and post it in chat.",
    "Kiss someone/something nearby passionately for 15 seconds.",
    "Speak only in questions until your next turn.",
    "Let someone nearby tickle you until you beg them to stop (if possible).",
    "Put on lipstick/chapstick and kiss a piece of paper, then show it.",
    "Do 10 'sexy' pushups (describe or show on cam).",
    "Tell the group the dirtiest word you know (voice or text, within TOS)."
]

# Would You Rather questions
SFW_WOULD_YOU_RATHER = [
    "Would you rather have the ability to fly or be invisible?",
    "Would you rather always be 10 minutes late or always be 20 minutes early?",
    "Would you rather have the power to read minds or the power to see the future?",
    "Would you rather live without music or live without TV?",
    "Would you rather be able to speak all foreign languages or be able to communicate with animals?",
    "Would you rather have unlimited money or unlimited free time?",
    "Would you rather always be hungry or always be tired?",
    "Would you rather live in the past or live in the future?",
    "Would you rather have the ability to change the past or see into the future?",
    "Would you rather be famous for something embarrassing or be forgotten completely?",
    "Would you rather have to always tell the truth or always lie?",
    "Would you rather live in a world where it's always winter or always summer?",
    "Would you rather have no arms or no legs?",
    "Would you rather be really tall or really short?",
    "Would you rather be able to control fire or control water?",
    "Would you rather never be able to eat your favorite food again or only be able to eat your favorite food?",
    "Would you rather be trapped in a romantic comedy with your enemies or trapped in a horror movie with your friends?",
    "Would you rather have to wear clown shoes every day or a clown wig every day?",
    "Would you rather have unlimited battery life on all your devices or never have to wait in line again?",
    "Would you rather be able to teleport anywhere or be able to time travel?",
    "Would you rather have super strength or super speed?",
    "Would you rather live without the internet or live without air conditioning and heating?",
    "Would you rather always have to whisper or always have to shout?",
    "Would you rather have x-ray vision or super hearing?",
    "Would you rather be stuck in traffic for 2 hours or be stuck in an elevator for 2 hours?",
    "Would you rather have to dance everywhere you go or sing everything you say?",
    "Would you rather live in a house made of glass or a house made of paper?",
    "Would you rather be able to breathe underwater or survive in space?",
    "Would you rather have the worst job in the world but be rich or have the best job in the world but be poor?",
    "Would you rather lose all your old memories or never be able to make new ones?",
    "Would you rather have all traffic lights you approach be green or never have to stand in line again?",
    "Would you rather be able to control the weather or be able to talk to machines?",
    "Would you rather have to live the same day over and over for a year or lose a year of your life?",
    "Would you rather have your first crush show up at your door or be able to go back and relive your first kiss?",
    "Would you rather have to hop everywhere or crawl everywhere?",
    "Would you rather live in a world without books or a world without movies?",
    "Would you rather be able to transform into any animal or be able to understand any language?",
    "Would you rather have perfect weather wherever you go or never need sleep again?",
    "Would you rather be really good at lying or always know when someone is lying to you?",
    "Would you rather have to eat everything with chopsticks or eat everything with your hands?",
    "Would you rather live somewhere where it's always 90°F (32°C) or always 32°F (0°C)?",
    "Would you rather have free wifi wherever you go or be able to drink unlimited free coffee at any cafe?",
    "Would you rather wear your pajamas to work every day or wear a formal suit to bed every night?",
    "Would you rather be 3 feet taller or 3 feet shorter than you are now?",
    "Would you rather have a rewind button or a pause button for your life?",
    "Would you rather be rich and ugly or poor and beautiful?",
    "Would you rather have the ability to see 10 minutes into your own future or 10 minutes into the future of anyone else?",
    "Would you rather be able to run as fast as a car or fly as slow as a bike?",
    "Would you rather have to live without chocolate for a year or live without cheese for a year?",
    "Would you rather be trapped on a broken ski lift or in a broken elevator?",
    "Would you rather have all your clothes fit perfectly or have the most comfortable shoes?",
    "Would you rather fight 100 duck-sized horses or 1 horse-sized duck?",
    "Would you rather have to always speak in rhymes or have to sing instead of speaking?",
    "Would you rather have unlimited first class tickets or never have to pay for food again?",
    "Would you rather be able to change your appearance at will or be able to change your personality at will?",
    "Would you rather have your dream job but live far from family and friends or have a mediocre job but live close to family and friends?",
    "Would you rather be able to eat anything without gaining weight or need only 2 hours of sleep per night?",
    "Would you rather have the power to heal others or the power to bring someone back from the dead once?",
    "Would you rather be able to live to 200 years old or be able to restart your life at 18 with all your current knowledge?",
    "Would you rather have a time machine that only goes back in time or only goes forward in time?",
    "Would you rather be a famous director or a famous actor?",
    "Would you rather have super sensitive taste buds or super sensitive hearing?",
    "Would you rather have to always use a fork to eat everything or use chopsticks to eat everything?",
    "Would you rather live without hot showers or live without your smartphone?",
    "Would you rather be amazing at singing but terrible at dancing or amazing at dancing but terrible at singing?",
    "Would you rather be able to speak to plants or speak to electronics?",
    "Would you rather have every outfit you wear be one size too big or one size too small?",
    "Would you rather have a pet dragon or a pet unicorn?",
    "Would you rather always be underdressed or always be overdressed?",
    "Would you rather have to announce everything you're thinking or never be able to speak again?",
    "Would you rather live in a cave or live in a tree house?",
    "Would you rather be trapped in a room with someone who talks non-stop or someone who never talks?",
    "Would you rather have unlimited pizza for life but can't eat any other food or eat normally but never have pizza again?",
    "Would you rather be able to make any one thing free for everyone forever or be able to completely eliminate one problem from the world?",
    "Would you rather have the ability to speak every language fluently or be able to play every musical instrument perfectly?",
    "Would you rather have a photographic memory or be able to forget anything you want?",
    "Would you rather be able to control time but only go forward or control time but only go backward?",
    "Would you rather have the ability to read minds or have the ability to control minds?",
    "Would you rather be able to talk to animals or be able to understand any language?",
    "Would you rather have super strength or super intelligence?",
    "Would you rather be able to fly but only 5 feet off the ground or be able to teleport but only to places you've been before?",
    "Would you rather have the ability to become invisible or the ability to become intangible?",
    "Would you rather have perfect vision or perfect hearing?",
    "Would you rather be able to breathe underwater or be able to survive extreme temperatures?",
    "Would you rather have the ability to heal any injury or the ability to cure any disease?",
    "Would you rather be able to shapeshift into any animal or be able to control the weather?",
    "Would you rather have unlimited money but only for yourself or have a moderate amount of money that you must share with others?",
    "Would you rather be able to see 10 years into the future or 100 years into the past?",
    "Would you rather have the ability to duplicate yourself or merge with another person?",
    "Would you rather be able to control fire or control electricity?",
    "Would you rather have the ability to grow plants instantly or the ability to purify any water?",
    "Would you rather be able to communicate telepathically or be able to project your thoughts as images?",
    "Would you rather have the ability to phase through walls or the ability to create force fields?",
    "Would you rather be able to control gravity or control magnetism?",
    "Would you rather have the ability to create illusions or the ability to see through illusions?",
    "Would you rather be able to regenerate any body part or be able to enhance any body part?",
    "Would you rather have the ability to control shadows or control light?",
    "Would you rather be able to speak to the dead or be able to see the future of anyone you touch?",
    "Would you rather have the ability to create portals or the ability to create pocket dimensions?",
    "Would you rather be able to control sound waves or control light waves?",
    "Would you rather have the ability to manipulate probability or the ability to manipulate reality?",
    "Would you rather be able to control plants or control animals?",
    "Would you rather have the ability to create matter or the ability to destroy matter?",
    "Would you rather be able to control your own aging or control the aging of others?",
    "Would you rather have the ability to see in complete darkness or see through any material?",
    "Would you rather be able to control your dreams or control other people's dreams?",
    "Would you rather have the ability to absorb knowledge from books by touching them or absorb skills from people by touching them?",
    "Would you rather be able to create perfect clones of yourself or merge with other people temporarily?",
    "Would you rather have the ability to control emotions or control memories?",
    "Would you rather be able to speak to machines or be able to speak to nature?",
    "Would you rather have the ability to control time in a small area or control space in a small area?",
    "Would you rather be able to see all possible futures or see all possible pasts?",
    "Would you rather have the ability to create life or the ability to restore life?",
    "Would you rather be able to control your own body completely or control one other person's body?",
    "Would you rather have the ability to become any size or become any weight?",
    "Would you rather be able to control temperature or control pressure?",
    "Would you rather have the ability to create energy or the ability to store unlimited energy?",
    "Would you rather be able to control your own cells or control other people's cells?",
    "Would you rather have the ability to see atoms or see galaxies?",
    "Would you rather be able to control your own DNA or control other people's DNA?",
    "Would you rather have the ability to create new elements or the ability to manipulate existing elements?",
    "Would you rather be able to control your own evolution or control the evolution of a species?",
    "Would you rather have the ability to see the true form of anything or see the potential form of anything?",
    "Would you rather be able to control your own consciousness or control the consciousness of others?",
    "Would you rather have a rewind button for your life or a fast-forward button?",
    "Would you rather be able to pause time for everyone except yourself or slow down time for everyone?",
    "Would you rather have the ability to know what someone is thinking or know what someone is feeling?",
    "Would you rather be able to experience any moment in history or experience any moment in the future?",
    "Would you rather have the ability to communicate with aliens or communicate with spirits?",
    "Would you rather be able to create perfect art or create perfect music?",
    "Would you rather have the ability to solve any problem or prevent any problem?",
    "Would you rather be able to understand any code or understand any language?",
    "Would you rather have the ability to see through lies or see through disguises?",
    "Would you rather be able to control your own luck or control other people's luck?",
    "Would you rather have the ability to see connections between things or see patterns in chaos?",
    "Would you rather be able to create perfect memories or erase bad memories?",
    "Would you rather have the ability to see the best in people or see the worst in people?",
    "Would you rather be able to inspire others or motivate yourself?",
    "Would you rather have the ability to see the truth or see the beauty?",
    "Would you rather be able to create harmony or create change?",
    "Would you rather have the ability to see the big picture or see the details?",
    "Would you rather be able to see the past clearly or see the future clearly?",
    "Would you rather have the ability to understand yourself or understand others?",
    "Would you rather be able to create peace or create excitement?",
    "Would you rather have the ability to see what's missing or see what's needed?",
    "Would you rather be able to see the potential or see the reality?",
    "Would you rather have the ability to create order or create freedom?",
    "Would you rather be able to see the cause or see the effect?",
    "Would you rather have the ability to see the beginning or see the end?",
    "Would you rather be able to see the whole or see the parts?",
    "Would you rather have the ability to see the light or see the dark?",
    "Would you rather be able to see the surface or see the depth?",
    "Would you rather have the ability to see the obvious or see the hidden?",
    "Would you rather be able to see the present or see the possibilities?",
    "Would you rather have the ability to see the forest or see the trees?",
    "Would you rather be able to see the journey or see the destination?",
    "Would you rather have the ability to see the process or see the result?",
    "Would you rather be able to see the method or see the meaning?",
    "Would you rather have the ability to see the form or see the function?",
    "Would you rather be able to see the structure or see the flow?",
    "Would you rather have the ability to see the pattern or see the exception?",
    "Would you rather be able to see the rule or see the exception?",
    "Would you rather have the ability to see the norm or see the unique?",
    "Would you rather be able to see the common or see the rare?",
    "Would you rather have the ability to see the typical or see the extraordinary?",
    "Would you rather be able to see the expected or see the unexpected?",
    "Would you rather have the ability to see the predictable or see the surprising?",
    "Would you rather be able to see the familiar or see the strange?",
    "Would you rather have the ability to see the known or see the unknown?",
    "Would you rather be able to see the safe or see the dangerous?",
    "Would you rather have the ability to see the easy or see the challenging?",
    "Would you rather be able to see the simple or see the complex?",
    "Would you rather have the ability to see the clear or see the mysterious?",
    "Would you rather have a photographic memory or be able to forget traumatic experiences?",
    "Would you rather be able to speak every language or be able to play every instrument?",
    "Would you rather have the ability to time travel but only to the past or only to the future?",
    "Would you rather be able to read minds or be able to control minds?",
    "Would you rather have super strength or super speed?",
    "Would you rather be able to fly or be able to teleport?",
    "Would you rather be invisible or be able to shapeshift?",
    "Would you rather have x-ray vision or super hearing?",
    "Would you rather be able to control fire or control water?",
    "Would you rather be able to control electricity or control magnetism?",
    "Would you rather be able to breathe underwater or survive in space?",
    "Would you rather be able to heal others or be able to heal yourself?",
    "Would you rather be able to talk to animals or talk to plants?",
    "Would you rather be able to create illusions or see through illusions?",
    "Would you rather be able to control your dreams or control other people's dreams?",
    "Would you rather be able to duplicate yourself or merge with others?",
    "Would you rather be able to phase through walls or create force fields?",
    "Would you rather be able to control gravity or control time?",
    "Would you rather be able to create portals or create pocket dimensions?",
    "Would you rather be able to manipulate probability or manipulate reality?",
    "Would you rather be able to absorb knowledge from books or absorb skills from people?",
    "Would you rather be able to see the future or change the past?",
    "Would you rather be able to communicate telepathically or project your thoughts as images?",
    "Would you rather be able to control shadows or control light?",
    "Would you rather be able to speak to the dead or see the future of anyone you touch?",
    "Would you rather be able to control sound waves or control light waves?",
    "Would you rather be able to control plants or control animals?",
    "Would you rather be able to create matter or destroy matter?",
    "Would you rather be able to control your own aging or control the aging of others?",
    "Would you rather be able to see in complete darkness or see through any material?",
    "Would you rather be able to control emotions or control memories?",
    "Would you rather be able to speak to machines or speak to nature?",
    "Would you rather be able to see all possible futures or see all possible pasts?",
    "Would you rather be able to create life or restore life?",
    "Would you rather be able to become any size or become any weight?",
    "Would you rather be able to control temperature or control pressure?",
    "Would you rather be able to create energy or store unlimited energy?",
    "Would you rather be able to see atoms or see galaxies?",
    "Would you rather be able to control your own DNA or control other people's DNA?",
    "Would you rather be able to create new elements or manipulate existing elements?",
    "Would you rather be able to control your own evolution or control the evolution of a species?",
    "Would you rather be able to see the true form of anything or see the potential form of anything?",
    "Would you rather be able to control your own consciousness or control the consciousness of others?",
    "Would you rather have unlimited pizza for life or unlimited ice cream for life?",
    "Would you rather be able to eat anything without gaining weight or never need to sleep?",
    "Would you rather have perfect memory or be able to forget anything you want?",
    "Would you rather be able to speak every language or be able to play every instrument?",
    "Would you rather be able to time travel to the past or to the future?",
    "Would you rather be able to read minds or be able to control minds?",
    "Would you rather have super strength or super speed?",
    "Would you rather be able to fly or be able to teleport?",
    "Would you rather be invisible or be able to shapeshift?",
    "Would you rather have x-ray vision or super hearing?",
    "Would you rather be able to control fire or control water?",
    "Would you rather be able to control electricity or control magnetism?",
    "Would you rather be able to breathe underwater or survive in space?",
    "Would you rather be able to heal others or be able to heal yourself?",
    "Would you rather be able to talk to animals or talk to plants?",
    "Would you rather be able to create illusions or see through illusions?",
    "Would you rather be able to control your dreams or control other people's dreams?",
    "Would you rather be able to duplicate yourself or merge with others?",
    "Would you rather be able to phase through walls or create force fields?",
    "Would you rather be able to control gravity or control time?",
    "Would you rather be able to create portals or create pocket dimensions?",
    "Would you rather be able to manipulate probability or manipulate reality?",
    "Would you rather be able to absorb knowledge from books or absorb skills from people?",
    "Would you rather be able to see the future or change the past?",
    "Would you rather be able to communicate telepathically or project your thoughts as images?",
    "Would you rather be able to control shadows or control light?",
    "Would you rather be able to speak to the dead or see the future of anyone you touch?",
    "Would you rather be able to control sound waves or control light waves?",
    "Would you rather be able to control plants or control animals?",
    "Would you rather be able to create matter or destroy matter?",
    "Would you rather be able to control your own aging or control the aging of others?",
    "Would you rather be able to see in complete darkness or see through any material?",
    "Would you rather be able to control emotions or control memories?",
    "Would you rather be able to speak to machines or speak to nature?",
    "Would you rather be able to see all possible futures or see all possible pasts?",
    "Would you rather be able to create life or restore life?",
    "Would you rather be able to become any size or become any weight?",
    "Would you rather be able to control temperature or control pressure?",
    "Would you rather be able to create energy or store unlimited energy?",
    "Would you rather be able to see atoms or see galaxies?",
    "Would you rather be able to control your own DNA or control other people's DNA?",
    "Would you rather be able to create new elements or manipulate existing elements?",
    "Would you rather be able to control your own evolution or control the evolution of a species?",
    "Would you rather be able to see the true form of anything or see the potential form of anything?",
    "Would you rather be able to control your own consciousness or control the consciousness of others?"
]

NSFW_WOULD_YOU_RATHER = [
    "Would you rather have sex with someone you love but terrible chemistry or amazing sex with someone you don't love?",
    "Would you rather your partner be amazing in bed but terrible at communicating or great at communicating but bad in bed?",
    "Would you rather have your browsing history made public or your text messages made public?",
    "Would you rather have sex only in the missionary position for the rest of your life or never have sex in the missionary position again?",
    "Would you rather walk in on your parents having sex or have your parents walk in on you having sex?",
    "Would you rather have sex only once a week or masturbate only once a week?",
    "Would you rather date someone who's amazing in bed but boring personality or terrible in bed but amazing personality?",
    "Would you rather have your worst enemy see your nudes or your boss see your nudes?",
    "Would you rather have an amazing one-night stand or mediocre sex with someone you love?",
    "Would you rather be caught masturbating by your crush or by your parents?",
    "Would you rather be the dominant partner always or the submissive partner always?",
    "Would you rather have sex with the lights on always or with the lights off always?",
    "Would you rather have your partner fake an orgasm every time or never orgasm but always be honest about it?",
    "Would you rather be known for being amazing at oral sex or amazing at regular sex?",
    "Would you rather have a partner who's extremely kinky or extremely vanilla?",
    "Would you rather accidentally send a nude to your boss or to your ex?",
    "Would you rather have sex in a public place and risk getting caught or never have sex anywhere but your bedroom?",
    "Would you rather have your partner be a screamer or completely silent during sex?",
    "Would you rather find out your partner has been faking their orgasms or that they've been thinking about someone else during sex?",
    "Would you rather have amazing foreplay but disappointing sex or skip foreplay but have amazing sex?",
    "Would you rather have your sex tape leaked online or your diary published in a newspaper?",
    "Would you rather be with someone who wants sex way more than you or way less than you?",
    "Would you rather have a partner who's selfish in bed but generous everywhere else or generous in bed but selfish everywhere else?",
    "Would you rather accidentally call out your ex's name during sex or have your partner call out their ex's name?",
    "Would you rather have sex only when you're both drunk or only when you're both completely sober?",
    "Would you rather have the best sex of your life but never see that person again or have mediocre sex with your soulmate?",
    "Would you rather be with someone who has absolutely no experience or someone who has been with 100+ people?",
    "Would you rather have your parents see your search history or your children (when they're adults) see your search history?",
    "Would you rather be amazing at giving pleasure but never receive it or amazing at receiving but terrible at giving?",
    "Would you rather have your partner be extremely jealous but faithful or completely trusting but unfaithful?",
    "Would you rather have to describe your favorite sexual position to your parents or demonstrate it (clothed) to your friends?",
    "Would you rather have sex only on special occasions (birthdays, holidays) or have sex every day but it's always boring?",
    "Would you rather have your partner always want to try new things in bed (even weird ones) or never want to try anything new?",
    "Would you rather be with someone who finishes too quickly or someone who takes forever to finish?",
    "Would you rather have amazing sex but your partner never wants to cuddle after or terrible sex but amazing aftercare?",
    "Would you rather be in a relationship with no sex or have sex with no emotional connection?",
    "Would you rather have your most embarrassing sexual fantasy come true or have your partner's most embarrassing fantasy come true?",
    "Would you rather be with someone who's amazing at dirty talk or someone who's amazing with their hands?",
    "Would you rather have sex only in complete darkness or only in broad daylight?",
    "Would you rather have to always make the first move or never be allowed to make the first move?",
    "Would you rather be with someone who's extremely attractive but bad in bed or average looking but incredible in bed?",
    "Would you rather have your partner be too rough or too gentle?",
    "Would you rather have sex interrupted by your parents calling or by the police knocking?",
    "Would you rather be in a sexless relationship with your perfect emotional match or a purely physical relationship with no emotional connection?",
    "Would you rather have your partner always want to be on top or always want to be on bottom?",
    "Would you rather have amazing sexual chemistry but fight constantly outside the bedroom or get along perfectly but have no chemistry?",
    "Would you rather be with someone who's extremely vocal about what they want or someone who never tells you what they like?",
    "Would you rather have sex only when you're in love or only when you're not in love?",
    "Would you rather have your worst hookup story go viral or have your best hookup story never be believed?",
    "Would you rather be with someone who's a perfectionist in bed or someone who doesn't care about performance?",
    "Would you rather have to always shower before sex or never be allowed to shower before sex?",
    "Would you rather be incredible at one specific sexual act or mediocre at everything?",
    "Would you rather have your partner always want to do it in the morning or always at night?",
    "Would you rather be with someone who's extremely kinky but only in private or someone who's vanilla but adventurous in public?",
    "Would you rather have to use toys every time or never be allowed to use toys?",
    "Would you rather be with someone who wants to film your intimate moments or someone who won't even let you see them naked?",
    "Would you rather have a partner who's amazing at sexting but terrible in person or terrible at sexting but amazing in person?",
    "Would you rather have to tell your partner every sexual thought you have or never be allowed to share your fantasies?",
    "Would you rather be with someone who's extremely experienced but compares you to past partners or someone inexperienced who makes mistakes?",
    "Would you rather have incredible chemistry with someone you can't stand as a person or be best friends with someone you have zero attraction to?",
    "Would you rather have your partner always want quickies or always want hours-long sessions?",
    "Would you rather be with someone who's selfish during sex but thoughtful everywhere else or thoughtful during sex but selfish everywhere else?",
    "Would you rather have to always initiate everything or never be allowed to initiate anything?",
    "Would you rather be with someone who's completely silent during sex or someone who won't stop talking during sex?",
    "Would you rather have amazing phone sex but terrible in-person sex or terrible phone sex but amazing in-person sex?",
    "Would you rather be with someone who always wants to try new positions or someone who only wants to do the same position?",
    "Would you rather have your partner be extremely submissive in bed but dominant everywhere else or dominant in bed but submissive everywhere else?",
    "Would you rather have to always have music playing during sex or always have complete silence?",
    "Would you rather be with someone who takes forever to get in the mood or someone who's always ready but finishes too quickly?",
    "Would you rather have amazing sexual tension but never act on it or act on it but have no tension afterward?",
    "Would you rather be with someone who's amazing at teasing but never follows through or someone who skips all foreplay but delivers?",
    "Would you rather have your ideal physical type but terrible personality in bed or your ideal personality but not your physical type?",
    "Would you rather be with someone who always wants to be in control or someone who never wants any responsibility?",
    "Would you rather have sex with someone who's amazing at foreplay but terrible at the main event or someone who skips foreplay but is incredible at sex?",
    "Would you rather be with someone who wants to try everything once or someone who only wants to do what they know they like?",
    "Would you rather have your partner be extremely adventurous in bed but vanilla in life or vanilla in bed but adventurous in life?",
    "Would you rather be with someone who's always ready to go or someone who needs a lot of buildup?",
    "Would you rather have sex with someone who's extremely vocal or someone who's completely silent?",
    "Would you rather be with someone who wants to experiment with kinks or someone who's satisfied with basics?",
    "Would you rather have your partner be extremely dominant in bed but submissive in life or submissive in bed but dominant in life?",
    "Would you rather be with someone who's extremely experienced but compares you to others or someone inexperienced who makes mistakes?",
    "Would you rather have sex with someone who's extremely attractive but bad in bed or someone average looking but incredible in bed?",
    "Would you rather be with someone who wants to film everything or someone who won't even let you see them naked?",
    "Would you rather have your partner be extremely kinky but only in private or vanilla but adventurous in public?",
    "Would you rather be with someone who's amazing at sexting but terrible in person or terrible at sexting but amazing in person?",
    "Would you rather have sex with someone who always wants to be on top or always wants to be on bottom?",
    "Would you rather be with someone who's extremely rough or extremely gentle?",
    "Would you rather have your partner be extremely jealous but faithful or completely trusting but unfaithful?",
    "Would you rather be with someone who wants to try new positions constantly or someone who only wants one position?",
    "Would you rather have sex with someone who's extremely selfish in bed but generous in life or generous in bed but selfish in life?",
    "Would you rather be with someone who's extremely vocal about what they want or someone who never tells you what they like?",
    "Would you rather have your partner be extremely submissive in bed but dominant in life or dominant in bed but submissive in life?",
    "Would you rather be with someone who always wants to do it in the morning or always at night?",
    "Would you rather have sex with someone who wants to use toys every time or never wants to use toys?",
    "Would you rather be with someone who's extremely kinky but only wants to do it once a week or vanilla but wants it daily?",
    "Would you rather have your partner be extremely experienced but tells you about past partners or inexperienced but makes mistakes?",
    "Would you rather be with someone who's extremely attractive but has no personality or average looking but amazing personality?",
    "Would you rather have sex with someone who wants to film your intimate moments or someone who won't even let you see them naked?",
    "Would you rather be with someone who's extremely kinky but only in private or vanilla but adventurous in public?",
    "Would you rather have your partner be amazing at sexting but terrible in person or terrible at sexting but amazing in person?",
    "Would you rather be with someone who always wants to be on top or always wants to be on bottom?",
    "Would you rather have sex with someone who's extremely rough or extremely gentle?",
    "Would you rather be with someone who's extremely jealous but faithful or completely trusting but unfaithful?",
    "Would you rather have your partner want to try new positions constantly or only want one position?",
    "Would you rather be with someone who's extremely selfish in bed but generous in life or generous in bed but selfish in life?",
    "Would you rather have sex with someone who's extremely vocal about what they want or someone who never tells you what they like?",
    "Would you rather be with someone who's extremely submissive in bed but dominant in life or dominant in bed but submissive in life?",
    "Would you rather have your partner always want to do it in the morning or always at night?",
    "Would you rather be with someone who wants to use toys every time or never wants to use toys?",
    "Would you rather have sex with someone who's extremely kinky but only wants to do it once a week or vanilla but wants it daily?",
    "Would you rather be with someone who's extremely experienced but tells you about past partners or inexperienced but makes mistakes?",
    "Would you rather have your partner be extremely attractive but has no personality or average looking but amazing personality?",
    "Would you rather be with someone who wants to film your intimate moments or someone who won't even let you see them naked?",
    "Would you rather have sex with someone who's extremely kinky but only in private or vanilla but adventurous in public?",
    "Would you rather be with someone who's amazing at sexting but terrible in person or terrible at sexting but amazing in person?",
    "Would you rather have your partner always want to be on top or always want to be on bottom?",
    "Would you rather be with someone who's extremely rough or extremely gentle?",
    "Would you rather have sex with someone who's extremely jealous but faithful or completely trusting but unfaithful?",
    "Would you rather be with someone who wants to try new positions constantly or only wants one position?",
    "Would you rather have your partner be extremely selfish in bed but generous in life or generous in bed but selfish in life?",
    "Would you rather be with someone who's extremely vocal about what they want or someone who never tells you what they like?",
    "Would you rather have sex with someone who's a 10/10 in looks but 2/10 in bed or 2/10 in looks but 10/10 in bed?",
    "Would you rather have your partner want to roleplay every time or never want to roleplay?",
    "Would you rather be with someone who's extremely vanilla but wants it 3 times a day or extremely kinky but only wants it once a week?",
    "Would you rather have sex with someone who's extremely clean and hygienic but boring or adventurous but not as clean?",
    "Would you rather be with someone who's extremely confident in bed but insecure in life or insecure in bed but confident in life?",
    "Would you rather have your partner be extremely experimental but makes mistakes or extremely careful but never tries anything new?",
    "Would you rather be with someone who's extremely passionate but rough or extremely gentle but boring?",
    "Would you rather have sex with someone who's extremely focused on your pleasure or extremely focused on their own pleasure?",
    "Would you rather be with someone who's extremely romantic in bed but not in life or romantic in life but not in bed?",
    "Would you rather have your partner be extremely vocal during sex or extremely quiet during sex?",
    "Would you rather be with someone who's extremely experienced but judgmental or inexperienced but accepting?",
    "Would you rather have sex with someone who's extremely attractive but lazy or average looking but extremely enthusiastic?",
    "Would you rather be with someone who wants to try BDSM or someone who's completely against it?",
    "Would you rather have your partner be extremely dominant but only in bed or extremely submissive but only in bed?",
    "Would you rather be with someone who's extremely kinky but only wants quickies or vanilla but wants long sessions?",
    "Would you rather have sex with someone who's extremely experimental but unsafe or extremely safe but boring?",
    "Would you rather be with someone who's extremely passionate but unpredictable or extremely predictable but reliable?",
    "Would you rather have your partner be extremely focused on foreplay or extremely focused on the main event?",
    "Would you rather be with someone who's extremely experienced but compares you or inexperienced but learns with you?",
    "Would you rather have sex with someone who's extremely attractive but selfish or average looking but selfless?",
    "Would you rather be with someone who wants to try everything or someone who only wants basics?",
    "Would you rather have your partner be extremely kinky but only in private or vanilla but adventurous in public?",
    "Would you rather be with someone who's extremely experimental but makes mistakes or extremely careful but never experiments?",
    "Would you rather have sex with someone who's extremely passionate but rough or extremely gentle but less passionate?",
    "Would you rather be with someone who's extremely focused on your pleasure or extremely focused on their own?",
    "Would you rather have your partner be extremely romantic in bed but not in life or romantic in life but not in bed?",
    "Would you rather be with someone who's extremely vocal during sex or extremely quiet?",
    "Would you rather have sex with someone who's extremely experienced but judgmental or inexperienced but accepting?",
    "Would you rather be with someone who's extremely attractive but lazy or average looking but enthusiastic?",
    "Would you rather have your partner want to try BDSM or be completely against it?",
    "Would you rather be with someone who's extremely dominant but only in bed or extremely submissive but only in bed?",
    "Would you rather have sex with someone who's extremely kinky but only wants quickies or vanilla but wants long sessions?",
    "Would you rather be with someone who's extremely experimental but unsafe or extremely safe but boring?",
    "Would you rather have your partner be extremely passionate but unpredictable or extremely predictable but reliable?",
    "Would you rather be with someone who's extremely focused on foreplay or extremely focused on the main event?",
    "Would you rather have sex with someone who's extremely experienced but compares you or inexperienced but learns with you?",
    "Would you rather be with someone who's extremely attractive but selfish or average looking but selfless?",
    "Would you rather have your partner want to try everything or only want basics?",
    "Would you rather be with someone who's extremely kinky but only in private or vanilla but adventurous in public?",
    "Would you rather have sex with someone who's extremely experimental but makes mistakes or extremely careful but never experiments?",
    "Would you rather be with someone who's extremely passionate but rough or extremely gentle but less passionate?",
    "Would you rather have your partner be extremely focused on your pleasure or extremely focused on their own?",
    "Would you rather be with someone who's extremely romantic in bed but not in life or romantic in life but not in bed?",
    "Would you rather have sex with someone who's extremely vocal during sex or extremely quiet?",
    "Would you rather be with someone who's extremely experienced but judgmental or inexperienced but accepting?",
    "Would you rather have your partner be extremely attractive but lazy or average looking but enthusiastic?",
    "Would you rather be with someone who wants to try BDSM or be completely against it?",
    "Would you rather have sex with someone who's extremely dominant but only in bed or extremely submissive but only in bed?",
    "Would you rather be with someone who's extremely kinky but only wants quickies or vanilla but wants long sessions?"
]

# Forfeits for not completing a dare
FORFEITS = [
    "Tell the group an embarrassing (but SFW) story about yourself.",
    "Let the group choose a funny (SFW) nickname for you for the next hour.",
    "Post \"I forfeited a dare!\" in the chat.",
    "Do 5 push-ups (or another simple exercise) right now.",
    "Compliment the person who dared you.",
    "Speak in a silly voice until your next turn.",
    "Change your profile picture to something silly (chosen by the group?) for 10 minutes.",
    "Tell a dad joke.",
    "Try to lick your nose.",
    "Let someone else ask you a SFW Truth question."
]